apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoice-ninja-public
  namespace: hdf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoice-ninja-storage
  namespace: hdf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
