apiVersion: v1
kind: Secret
metadata:
    name: invoice-ninja-secrets
    namespace: hdf
stringData:
    APP_KEY: ENC[AES256_GCM,data:uMe9ikEPoDOJeEou1p+NbD9RodzN09GX/6nmKWATUqm4zlaGP7sNIOD3KEy5nid+ixYH,iv:exZxoukWdFyWn+KKOfMNC/z+Lf4z6ktMGykNjs7o+bA=,tag:2VXFpvTVuafn1FFztywzvQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:cZgNyUSQo1A5BCNqNQPmfVBg84enA46mvKrbSafEKTc=,iv:XycH1d2FbBY8tNd86WrYfgUOVN7MHS/7yD1TqOE3uEg=,tag:A84fzIBD5D8oAvIXThmYwg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nVP5eeQQA86cqWBAzQFM5jroysXEtH7DKiz94Qs3eaI=,iv:cX6CgJ0JlJwn++h1o+KyFpPC2MCKgdDbtNPjoszQK3c=,tag:jeacXMurcmgYlwB6x1dYjg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rWL2082MLqx9WLdsTy/YTKm4B1RbJVVi08FOGutUELk+XvL7gCPLNo0aTyevAHIb,iv:wfy1Kl1s6o0JNvXSJW5kVF4pzgfbQuNg9WiYfySwdDM=,tag:QGq2CpbB+7AjZagdteoeOg==,type:str]
    IN_PASSWORD: ENC[AES256_GCM,data:sIc93BIfQAWsTvKljVmVhe4DO4pwLp5JlSgGe3dFvv74bexUdcBjHTTtGH1uCJK0,iv:K8Rhd543usvAdsAaL4ZBCNrAahUN8gAy4FuP9e75MOU=,tag:JTSvNPU449nYq1qL1VpUCg==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UmVVQnR6VEhiajh1WHhP
            Y0F6bUNJSXNYTXpSdEE0THQreWtWcTAwcGlVCkZ5d09NVTRyaFRZbDU4WjhkUW15
            ekVNbnlCSFVQRUMzYS9tam1iNjJ0elkKLS0tIEdoa2N6cW45Zlo5dENNNlRhTzM5
            WEtiNGJGOTZ3VG9mTW9PamxETUhCUVEK1iiqA3d20jweKXlwQ88EHVKiuvodoNWd
            Rb6o9L9Oim7fIJY9hXAlR33PkUOVgjwxo1M6vsf0lgXeYc9Py2Q+EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T02:41:18Z"
    mac: ENC[AES256_GCM,data:yZAFnisAkWWwdEsgR3jg3MMlyxHDTPFUgEfez+QfJfAuaiUJcQQTulsi051ie6DIn0wEBOK+Ygd5X9TK6h17KLMYY5RoUly1TwHGCxOTVKlBhj2edsLgVqaLG4hhgROJk6vxZucST71lnrBmTjbXfsg0zrwc36TUATuo3GWAEqs=,iv:bV2eBLg4zV5t2gh7n7nthujjNdiCiwLc4Gq3qKcVdSU=,tag:W1s18gyLSOaXoXhY+AzFlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
