apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - alertmanager-config.sops.yaml
  - helmrelease.yaml
  - ingress.yaml
  - loki-datasource.yaml
  - homelab-k8s-overview-dashboard.yaml
  - homelab-databases-dashboard.yaml
  - homelab-app-versions-dashboard.yaml
  - homelab-pod-logs-dashboard.yaml
  - homelab-proxmox-dashboard.yaml
  - homelab-alerts.yaml
