apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:o6pYHSM=,iv:UNKJFr4nifdJoRUo/ytlKxMks4RapsI4atI/DkgSKzc=,tag:ZzfmJEwrzpnjumd/iwsbeg==,type:str]
    admin-password: ENC[AES256_GCM,data:wdlxb6KtxFf+zHT9aMU2sXsmpFxw3f2GLIJnZncHkZzALAPB,iv:ivmjPt/YAk0IJc2GfYUCff1yLw31xrQEEv+3045daQs=,tag:WrYYfQdloupUZqJwviAH0A==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTGJaUVo0MTZ6V3JZVHZs
            OUJ2cmhkK3RFUURsNWVWQWdRdk5HSTVRTzNRCkJZNUxSeUowaDRlRy96RWNTOHBR
            T0tPQ1lIUG9TeFJWN0ZRSGx2NlVteUUKLS0tIEQ3Uk5YVWpYakdHZTJQMVYrQ1JC
            cnlDRWpSK2kwaXdnd1JwR3NIaVRsSzgKA9h/ANwU8yoAH2QjpAW0KR7xamlfisCQ
            y0Qjd7akl9rl/9WJ8mQhb0ruAYuoT9cX7JF1jDxjaTWLJkcClpq1Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T02:50:02Z"
    mac: ENC[AES256_GCM,data:Hz4+k+C0rlxXReNbA11S1OgVah/Pk/bL0VOOqmbbjup//WCZkk9Lo4Qtx3rTqESBhNr4nyq3dyNwelXBk4dj1p7BMn1GSrvTBNv3lXhYsLUnVD29k4hm93gEvToraQYe8dq8PdriHZPrcsqWT7eaXlKJ0jg6O1f8j93sFgwGKEQ=,iv:o6OUFlY896Ahals9SQ1awBMQgrFUvhtTrrawzwQ5940=,tag:ZWoZtIocTPB94ZBp8HGpFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
