apiVersion: v1
kind: Secret
metadata:
    name: penpot-secret
    namespace: apps
type: Opaque
stringData:
    PENPOT_SECRET_KEY: ENC[AES256_GCM,data:njlDBwtlZo4jbxe8PADyfRVe+A8+sOC19yXPZ1OgLv0oI7lvOHYwR5jLgGi+b2DfA8/TBvnEmRDEcxwF01iT3Z9+BEE7PEUPO03e+/PstvqEB/cf+ry/zw==,iv:c7t75mOUgFUzexEhhDqt4bL4N3+kLSYEqoMvqFBP+LE=,tag:vwzemBQJ9FC4HuNgcV/4wQ==,type:str]
    PENPOT_DATABASE_PASSWORD: ENC[AES256_GCM,data:G8k1GtUTUy7IKLgmIdfy1BWH8zyvH2t8dKRQhlHpWNk=,iv:CLtkO9M5WlbQN0fxn0nJaISvUaIJaRkv4PvWexN4y7s=,tag:UlXwq25PkiD4iqNxDPHbQg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:k3bFxPO30GhoPp0Z1pAj5Ist111Fns3Ny2qjCDgRDrw=,iv:zl1APg7EVUyO/mydwpVzXhx7nzbq5MI1rQW7CKwSQ+s=,tag:2b9kdOdk17B8n3shWCwbig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wj1YQsT1sVwK/W+ObB6KBNK5aA5vxtCY2R3toqZmyHdev5xIhGu3zr24RxjItCn9,iv:hQ7aR/a0oxI0xYd/P+Y3Kphk4JePXJybQYJ+I7A0LCU=,tag:BjOjbhimkEOUjpn7yr3NPg==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaDZIWEZhSGxmOFJCWnJ5
            TkJsRjRSdmxIZ3gzVU81Zm81MEpQUnZQT0I0CjNiOFd3d1plVnB6UkpENzVqQXhH
            YVFSUXB1NHlqSW5nNVRMbzZpMmJQcGcKLS0tIHo2VENSeTIxK0VyZmVXRmpvVHVT
            Qko2bnI5OE1NOEJUQXNSejh1YjR2WWMKqGjDghvLcXWxlsYBL2fNySpWwfTweYc1
            8aVdLEU9em8UkCJnaV1m+GBoPgBM7sWQTbm/39g3gqwqxaolCRRWYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T01:10:14Z"
    mac: ENC[AES256_GCM,data:Xnhw/Alx8bO9IY237Gdm+pJ2aK+B7cc1T4XQTJZsmItV7D2twK48a3QmBIP0YOvwNkAVuHrXgHN/ydUx4+bPdERjnFH7ww7dPnKlmEIpMNB9zQ/HtEXwpv9shIDEEiv9+9co8zJZE+RIB+27Y3TcJkbCAuf91IJaIvOKPaIFL/Q=,iv:FL12OOITmipP2jIvmP77tApXKJXzj6AmRwHvO1AokY0=,tag:TGMmjNJcxHC5TwvUssrk2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
