apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-shared-portal-state
  namespace: auth
  labels:
    app.kubernetes.io/name: tailscale-shared-portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
