apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secrets
    namespace: media
type: Opaque
stringData:
    LIDARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:KkB4UnPJI9T/Sq+GWSn4tbzb90fW+psjjAPg76muO0c=,iv:pXneWwcawFscLe1tmFcpkqkJG+/cfwlgZlba2ZyaroQ=,tag:yNtdB9Esy8UGzLfowqGRyw==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbEJPNXFwb0JlQmhuallk
            MTExM3M4UDBNMUViS1lnaDE3U1Y3b0U5Q0FZCjc3eDlBSHF1V1NnM0V6WmcyVUtW
            MWNwM1p1RHAxV1NLQzlpRDZ1N0NGVHMKLS0tIGN2clBOc3RsQlVzd0lZa2lLam5D
            c1luUFVxdi9pWk04OXRQZ0VaYnR6VVUKY9sLvnalcKthlita4J7PKFXGHD/+XP0J
            mk2PPzDEBim30F/G5E9lqAirCmp3iyOMIMH7Wxl35ua51UXSiOzaRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T22:49:31Z"
    mac: ENC[AES256_GCM,data:kBDditTRhw2515ZBr4t8DIzjrSXqA69BS74cRuieJTFi0IeM//1G6zMlINnPbtpZcpYCYv0LugCfuS9uemYWcNBJus9T+UdOLxIzxi+APdvb32ikHGq6E6tM1H5Hg2mL5WoLUeMGDYB3sDt4QROv90nbaYBp9ESxC6T65cV0Fic=,iv:ej6vc8PGAuFn8BYfSFgS3QKy7Yl+aIevCqHS/NeiW8o=,tag:BKoPwrFHd85jTG538NmTGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
