apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: registeel
  namespace: internal
  labels:
    kubernetes.io/service-name: registeel
    app.kubernetes.io/name: registeel
    app.kubernetes.io/component: mariadb
addressType: IPv4
ports:
  - name: mysql
    protocol: TCP
    port: 3306
endpoints:
  - addresses:
      - 10.0.10.91
