apiVersion: v1
kind: Service
metadata:
  name: registeel
  namespace: internal
  labels:
    app.kubernetes.io/name: registeel
    app.kubernetes.io/component: mariadb
spec:
  type: ClusterIP
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
