apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secrets
    namespace: media
type: Opaque
stringData:
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:5Ko3+/lmP+VDVzAasIZIznDV8Z8+IQDHadAaX2rzfko=,iv:UF/uz3Wy/xPsJ+VlmXyQhraTL0klhMKXSJy7Qui21FY=,tag:/3ixyz2rmnYkyDjBAGw33A==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvREs2RVJBRlB0TXFtQUZ0
            SVcxNUJKbVNwR0RvM3dBYnlqT0JzN1RZUEdRClR4TW1GUGxJTmJpUGp2RmFvQnBy
            enRoLzVIdU4yTTM3YXlKSDBSTURDbkUKLS0tIHRQTXZzNlJtL1FRa1ZxcEVFZnBN
            ZTZBNVQvajZKZDduWmhtMk50b3haZVkK/Afpp4S4NZgkgVG9B1pk53iaXwxp0iCB
            pLJnXjLFriVg3BybcfE5tw4XdTazQXm9b86RfBQkunTnkOmlXHCFOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T22:03:47Z"
    mac: ENC[AES256_GCM,data:RzNFcw1dowxDfJ8En8T8Qf7ZDRZjfr/vBRyN0ddO06ohdKIcMi+FiGJziayKLO7cS+W6jrbOYhC+CI0VcBqCuRu3dkXTblagcFIVy6gJe6HZAKu9K1yDQU9BtzGWEJmASON4u3cvRzVguX1j/WVT4YZLjQHmqqGWaTE4HLbBDiA=,iv:iKep4Uh9xT6VMK8iqJKHwls5fUfnv15UEqIs5Yuegl8=,tag:+Ar4QAZkOgtSQWGZxtFf/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
