apiVersion: v1
kind: Secret
metadata:
    name: romm-secrets
    namespace: media
type: Opaque
stringData:
    DB_PASSWD: ENC[AES256_GCM,data:Wpl72rzMRcHyICWRnNbzbv3t9gGvZpmhhcHQEidJLU4=,iv:RjkBbSDRGPqtVxmOGUVRAzCyghj/zYH8ZMs7w1+EBTo=,tag:BWxxBM/+4QWL4YH6IdvgVQ==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:cneBhF+7Ht924at45gWEk5OrOomdIyUgUl3iiNidsO7lS8+yjsHGKVUfTrsFitOPeohMYr5PLZ0MzUN0Af32Kg==,iv:/k02jbxmUkPLLRbgB26UW70HStF3iSdBDN1lZqO60Nk=,tag:irl+PbIEAL7bP13lITlzFw==,type:str]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:sJLlZyP77uO7JKbk32R2UEWamaw8WnDR7zwqPBIZ,iv:0axanLmmeFN4ZkvmK2yME4f2Pyym+mvyyni3SLLBcHE=,tag:yunlhTtpmXBpjZaZeaZPLw==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data://vcSbzrVFD+7euzO1Ty6Rg0AzAvaWaC2O3+DEGG,iv:UVBbSYqFW8kuy92pWSS52dgWiik3ugcA2YkvgCauWQ0=,tag:O1tS1n+kVpzp1ULGHZZq5w==,type:str]
    MOBYGAMES_API_KEY: ""
    STEAMGRIDDB_API_KEY: ""
    RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:eGGfaz4pUGGAVAH/QQH+/sdzL+pch9YDlu5pKe5M63I=,iv:qfLOox+E4NRpkfpyLjDB3wzYXI7HLQGZ/ZGT7m5ZK30=,tag:J1tsPGptfyUpmPs/HaZ6lA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:ypqRQODO7ZJTM2oe33TMSzaOhArATJ/MFqei+GmeZSa8Zor3,iv:rWPL5vFrWMHkhq0irzb/Yaju0gVG9hRItoMc5j/IGVo=,tag:nSFw6OmNf7wzv32OVI+s8w==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:eTKbLxBQv1h9JE0JP3wSeBygekn3lt4nvxwLrCOJeUc=,iv:K/LdwM4ben9UEbI4zWGd3vYi5KP8btILlhVXVqPwlcY=,tag:EB8cCLGWh5wODCgg4EWIyQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWEpnaDZTb05rVHdHNXNz
            TlVqd00xQVVQYmlsb1pMazdaM251aDJLK1dvCndnK2tyVzMvdDcwL3BqR2tnT3h4
            RVpTQ2RCRmwrUDJ4V2ZxT1RzODBFK2sKLS0tICt1c0lzZ3lmNVMyeG54UU5kRmNh
            eVdrYnQ4QVFmSVo5dTBjTWJJQnhOdncKxWRBt3BqfmdA/sUrd4j9Xh3EsoL3VEvK
            ROdI8cxZNED4816EuM25952pbvLLmjUCKXvwIWeJy2ULjrYeGtDCPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T06:35:06Z"
    mac: ENC[AES256_GCM,data:0T7PbeS0BAo+uMJ8MgvphAr7zo6Etimk/DcGtcGRelAMxKpMhTVkwCJnnF8RXll7+ppL6KRg58zYKpTBysYU3VDHZX1jSwZG/NDBFcxHN/I/7Quub8vUnH7kOXHrPlq2PD9q2L570z7DNPilL7ZPRgsI95DYNGnpjbJWYWjL1/A=,iv:q6OWT8Qj4F+8NQM1YlytV2Bp0HNtmtppRXkMnsIejIk=,tag:/dusiAcUVDmVnE5Ef3x4aw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
