# Same admin user/password as set on both adguard-a and adguard-b.
apiVersion: v1
kind: Secret
metadata:
    name: adguard-exporter-credentials
    namespace: observability
type: Opaque
stringData:
    ADGUARD_USERNAME: ENC[AES256_GCM,data:+8ASZQuL2w==,iv:vefK+bt1lf8ILmq1e3DM9w9PfpQlFoKOgWbRCYd70w0=,tag:zOPE6QI6MHtGt1P9UKBYTw==,type:str]
    ADGUARD_PASSWORD: ENC[AES256_GCM,data:OmKLhbMC8cMYsAeMzQyhXeTDtxBERkCq,iv:ZlWPCvIyqt2+L+U2aICBQu9lmMdG0xUORk38Fa6IRTA=,tag:N88QIboQs+1iV+S4d/IpeA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QUVjNWRCUDFCcS95TWhy
            ZXkxMGtBaFlkcWF3UmkzeHpNT3c3WXdEV0VVCjZJaWxMYlZMdWRZVFROQ2hrSnRC
            WmFTa0Q3U0xwM3QvbUJXWCsyMzNnQ28KLS0tIFN3a2ExMEhJMUZacnpFQkVpSTkx
            bVlZRDAwRVYybHY1RFJzSW1HN0I0ejAK0csngwvnFwl49bmb1GHyhjF+RVJtazD9
            k9XJU3ORPTA+f53AWaxmnyqpTBJV1B0BpbUu1oD6Qf/j7VGQmyUD8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:30:42Z"
    mac: ENC[AES256_GCM,data:Qyuo8D8nffQ2dZls6LwZRi3zzs1Mw50c8ba0LuiWDxHw1Kc9RQLexQ5ZjTdNECJX2BwHv4golsr5fceDfrH74+wYOpwB2x2wj7lzx1ANu+BAuE99uafj6lH1g8BvG1EY7XY0qbrnRqoZkxerJiuTYnE8zoEmRVHajIxRzg5JuKQ=,iv:RWp5K7UsiykXVa7ZC20dEazIclFACrwCekqdNvy9Jco=,tag:ZpU7zXDnmkQv7+py7ZNxuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
