apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:oiQlqEzwgJor,iv:Ksy7uCisuVTxDtlD+V0zmhqdAOlKAj/BK7WCcPVID2E=,tag:4fo7NPNF9ReVSZHVQoXBgg==,type:str]
    client_secret: ENC[AES256_GCM,data:BUKklbL54DdM,iv:mCdOu1RUzdAgdSc5YeZJm9yExTVmNbeWmiJec+Dnn88=,tag:7WMNqMSqldQbqukX8GgFrA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa0hmWnd2UnNvWVdRdkkv
            azZ1YVliNHRTK003VDBXbHRjdjNTMjIrMmpNClZtQ1ZaUWQ5K3Jsb1Q3OHIyc3Q2
            YUMxSGwwaEIyVEptY2JqSGVIdUlPbm8KLS0tIFpPNjN0YXFVdjhtemxJWE9qcG9x
            b0hURThpejZtc1NpNEhKTHdNYWgvK2MKf9GgCu7J9KsakYCuztHfivKy8zQ/CRrJ
            QaCQSiWCNgvZTDnRwR4/s9lsgfAM2mRMkQJfaj0vdFJEcxD37xyGHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T00:53:41Z"
    mac: ENC[AES256_GCM,data:wU38Qoq+7oBaDm0a040EZgnDRegSCYWnPYwa83XHkuE2b+HRfolB67qes++j9+v1m5ew/5C8eZm8DxeEzxlcbd4S4MQKnOS34OIuaPtPou0/V3Z5Hn/APWsedX8adZe5GhWqodCd7wPw0WZ36A5Tk2HWvbAixLcwtDi9gzmtz54=,iv:HsKKP90jDOyF6t91jx9TLX3Yd45wDbhQ4kUsPKqeRqQ=,tag:2UYZFMdhGD0V+1eFxD9Ahg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
