apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:YTjh7IlwA7NnvgC1aguBK68=,iv:y90qMd0rX3fKCYfmUx3YXfMqJNau7NBoaxR/o9qa4aw=,tag:pBwwuAaRKUh/RT5BLs7xkw==,type:str]
    client_secret: ENC[AES256_GCM,data:Ffg6B6HwzJzpjaNYNSm7P1q9FLEeDCYXMOmOoXtIql5ECgw6ITy2LVEG1vdpuhjHTae4uDJIgqYOR1kvJ/b9,iv:7obbACdxs1AhFprgwu8PipTqmVxnqUp0rB5FsbTLJMs=,tag:ne5o8l05eOYpautUNdDCNA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa0hmWnd2UnNvWVdRdkkv
            azZ1YVliNHRTK003VDBXbHRjdjNTMjIrMmpNClZtQ1ZaUWQ5K3Jsb1Q3OHIyc3Q2
            YUMxSGwwaEIyVEptY2JqSGVIdUlPbm8KLS0tIFpPNjN0YXFVdjhtemxJWE9qcG9x
            b0hURThpejZtc1NpNEhKTHdNYWgvK2MKf9GgCu7J9KsakYCuztHfivKy8zQ/CRrJ
            QaCQSiWCNgvZTDnRwR4/s9lsgfAM2mRMkQJfaj0vdFJEcxD37xyGHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T01:01:38Z"
    mac: ENC[AES256_GCM,data:LYhV2EXQGWN/Y4zoZGBPMpEXB4LAKsy/par31XtvjO4O9V6ZzsB0JooLYtXi8e4wd1wQXAg7UUEFH2FD07olBlgCjfy1fdvvyqfl419vbzkbAbm6iUkhgpvcfhw/GcZGL7QBEgZvWC4LQPEa9VVMUgvojcSCH75QGOLq/JIYcvQ=,iv:goJNOmoCJ7mpuKv3DQy+9PSEVWpBUC7MpX08l77NwPg=,tag:o5MAw6MPKVd6hPcftbRuTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
