apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pocket-id
  namespace: auth
spec:
  entryPoints:
    - websecure
    - websecure-external
  routes:
    - match: Host(`id.mcnees.me`)
      kind: Rule
      middlewares:
        - name: public-chain
          namespace: infrastructure
      services:
        - name: pocket-id
          port: 80
  tls:
    secretName: pocket-id-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pocket-id
  namespace: auth
spec:
  secretName: pocket-id-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - id.mcnees.me
