apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: auth
stringData:
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:kagCMK7LGf2hBR7Z1GbQuHn279tVOOo0xo4vbNlxLjpDQHLEledZ59gCP33MqIh9RVcNSqe80b1Ng7LSxDYqHLylWfNtyuQeBlTF+7sF7A==,iv:Hhe4d49IyjA0Ym0Flawf9b2BB0MEZC42BUtOETnzn0Y=,tag:SKIb8I+CjJG4EUiCEzCkcQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:qmImTVl9hoo9vEORd3GRAPm4z7GSlRObRXjJ5IHbeno1uV/NGuxje+hiyQ==,iv:TgkgXc7cCiX5hKSGXZekuV5OaBzanvOKKI46MRSY56Q=,tag:/p9x1eJej0BXPTfONdTONw==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWnpuTDBMbWs4MWZETTRw
            NzdSNHhkVnpRc1lMMXhXTnhKek43N3RGbGhjCnhwaWZpRmxweS84YW1hbkQ2Mlhw
            ZkVKemU2VDIrenVwWVhOVnZodmFjZzQKLS0tIG1LUmdENmlORldKOXBCTnFHbFBx
            S04rUUQzNm93MVY0MXdKVlVoR0tvVmsKFlZNvjswoDgVkpVC4oILKyy5rZOeYfrM
            sKfgY/y3XLZdqvTJwwggxUwQ2qXnUgOPhZ0AyzjEmnhZFxncRrZThQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T18:41:23Z"
    mac: ENC[AES256_GCM,data:e8RD1PCK6uzUUUZJHhPUASC6AwtrBs6eDoLQfSB8BmeTg/G6eJ3g/GrFQkT2ecHjl6vq6y13qq/iUGxoqFjo6s1XXFOugmlIrhQbda0XFl6762nL0RN/9+VH/URszgiiih9AB3B4EgsVyp0qtgc7ALyq+V5TxzOwbfJL2sB++Rk=,iv:CBzljjDqdk0iuw5cXcOZ2j4LpQuFIzjRT1kwsWVwoKk=,tag:8/J4H0nMc1oDZbJryJF+gA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
