apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: auth
stringData:
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:kagCMK7LGf2hBR7Z1GbQuHn279tVOOo0xo4vbNlxLjpDQHLEledZ59gCP33MqIh9RVcNSqe80b1Ng7LSxDYqHLylWfNtyuQeBlTF+7sF7A==,iv:Hhe4d49IyjA0Ym0Flawf9b2BB0MEZC42BUtOETnzn0Y=,tag:SKIb8I+CjJG4EUiCEzCkcQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:55e9w2e3a3dx5hl/wc39uOS5GQ5UPtpnSKOojGbFSnd2r1+954jEMpgEhcs=,iv:MOo5/zbx858DkkUZVKQ1FfZh2uy/wh1Lwri3mX4a15E=,tag:PBB3IRus20lDg8ldm7QdHQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWnpuTDBMbWs4MWZETTRw
            NzdSNHhkVnpRc1lMMXhXTnhKek43N3RGbGhjCnhwaWZpRmxweS84YW1hbkQ2Mlhw
            ZkVKemU2VDIrenVwWVhOVnZodmFjZzQKLS0tIG1LUmdENmlORldKOXBCTnFHbFBx
            S04rUUQzNm93MVY0MXdKVlVoR0tvVmsKFlZNvjswoDgVkpVC4oILKyy5rZOeYfrM
            sKfgY/y3XLZdqvTJwwggxUwQ2qXnUgOPhZ0AyzjEmnhZFxncRrZThQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T01:27:50Z"
    mac: ENC[AES256_GCM,data:F5uM1xfH6J8sFeGI5ylLmXJvEDgl6pn9ohlxGEepwRJkr5VqvyCPDWlDx200b+MLgGO+lb2ICHp/IMnVV2wE6ooGW+4AO5aSmnCcrUbF4E1ZPsmozZTRhG/4K7oe7DOV/oFCeXKDi/hqXJTDSJoMkRorlKWrgBL7BrGHoYpJ9XY=,iv:i/7W47xXbcUC2Oc6fpI/BCOqg9Q6j4iaRMgWE+0OQgs=,tag:yPPLYKulP9+7g9FflP7H/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
