apiVersion: v1
kind: Service
metadata:
  name: pocket-id
  namespace: auth
spec:
  selector:
    app.kubernetes.io/name: pocket-id
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
