apiVersion: v1
kind: Secret
metadata:
    name: craft-mcp-upstream
    namespace: toolhive-system
stringData:
    CRAFT_MCP_UPSTREAM: ENC[AES256_GCM,data:WS3WYpS8OhbLlDlH6qORCaFDnMufBW7IiemHwnEBfZivS4xicBtXVi7h,iv:saRYJT6o6R1+6CckF94uajZXqvrHg5lRroFnFlaK5vk=,tag:yYtPTb/SRG0BGVu9aZxZFQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbjJPbkJCZ01DQzl3U1pO
            RWIvcHhLOWw3dEJac2pLZHRUVTZ4V240eVJ3CmExbGRaL05oUTIvQ3VpTXJ4Tk9n
            MHMzYzVoYjJIaTZXL1Y4Zy9qOTVERjQKLS0tIHlwekFuYnNSZjgzSHFIL1hQV0Nn
            Z0pDVVdleDRJNnlUNktpTjFMMWJpR0UK2lepjLDUAOu2fzHmNYYeq398ebzgBZ8l
            YYKR9GWVWoIj6PMZmvs9JUC7KVcqvJb7EIY3NHBUU3mCxDYjPauv8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T17:01:24Z"
    mac: ENC[AES256_GCM,data:97edgHZcEhW6mxcQy0mIlZ3DMw7Cj+rD2gcB2EM/YaG+Wt7uT7TPUF07SsKNq0cBdr1T5Cu7EeJDBy7aNO9rDWSvs0LgoYfjMw8zYNujJ1GsDAITyqijUi9bcoLhIRkPrxZJglNJw+QZtDfrBRHhjOeXUHKF/LCq58QSzPICBAo=,iv:nE1Bv8NLUp92Uz6cHImc7ZFUGA3P40+XaRWEHRULVkM=,tag:1XDhg6jryTkY9edpB6jyGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
