apiVersion: v1
kind: Secret
metadata:
    name: craft-mcp-upstream
    namespace: toolhive-system
stringData:
    CRAFT_MCP_UPSTREAM: ENC[AES256_GCM,data:fCTKyW6Hp3kv8/aGhC5J8bcv/YQ0nF4RAw==,iv:vUTu9Bx+IpKIU6xYgAp6oFrBhA8CQtDciYwOeddYQug=,tag:nUJzk7wZhlMg+3KOq1lYoA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbjJPbkJCZ01DQzl3U1pO
            RWIvcHhLOWw3dEJac2pLZHRUVTZ4V240eVJ3CmExbGRaL05oUTIvQ3VpTXJ4Tk9n
            MHMzYzVoYjJIaTZXL1Y4Zy9qOTVERjQKLS0tIHlwekFuYnNSZjgzSHFIL1hQV0Nn
            Z0pDVVdleDRJNnlUNktpTjFMMWJpR0UK2lepjLDUAOu2fzHmNYYeq398ebzgBZ8l
            YYKR9GWVWoIj6PMZmvs9JUC7KVcqvJb7EIY3NHBUU3mCxDYjPauv8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T16:46:19Z"
    mac: ENC[AES256_GCM,data:5ap5HtBk6pl+dSikUWTFje7UWdgR1p6ERDIHXxSM9Va/KzHPUFZf/cgYP/9Xs3V/kPCQ5EJ1kYEgM7GglQuDxIRIPqeIhtLAxaGSDCoXNkgRgmEDdiQ8SvQFheQTt+VJgIW97Nu+aLE7P35YICFe7pKzktcdJav6c6W19o1NPxA=,iv:JvHpRFXhr9DrcPu657A1uGElyv+nbREyEc5av4eueg4=,tag:Ma2nctULZzA91zG6nyWLzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
