apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - events-rbac.yaml
  - helmrelease-crds.yaml
  - helmrelease.yaml
  - gmail-mcp-secret.sops.yaml
  - toolhive-auth-redis-secret.sops.yaml
  - toolhive-auth-valkey.yaml
  - toolhive-mcp.yaml
