apiVersion: v1
data:
    password: ENC[AES256_GCM,data:OLEF4EatpGWCWrRJl+2OAlEphDhmOtwkBFqq1Jg3bh/PNAY9p+FlyAQKvEFkWXeFXfj1dTFYMxgmp2a1,iv:BG5yrhlboPQbZ61XuwwBcgubvQoh1y0UwXvE64VShAY=,tag:OS+Hvn+RNXtEiKdanVK8aA==,type:str]
kind: Secret
metadata:
    name: toolhive-auth-redis
    namespace: toolhive-system
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTEpTejJOTTlUeVc3TEtE
            Wk1icngzSkNuRlllWDFaOHEvUm83ZVNiaW5JCjlqcnpweW53d3NBR1pJMUJpdW9j
            QWF1K3lLTTFxbUF6ZnF4Ri9JRHVsbWcKLS0tIERLUEN0UHo5dzZoaEI4WU9mWjE2
            Ui9rMFVJd1dLOEdBQXZjSnJwTlRrbFkKBbuDBGH0tuc1utZ+5V4LGffqT/SxJd3Y
            YhUGXeKJTxC8iHzq8bLpd0HQYEQWtg/4tq+WVYH0aRBeoYPLmuHk8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T15:54:52Z"
    mac: ENC[AES256_GCM,data:LGlj4ycBKhzv4WF6qSe/N8CzpplByOzqG11Xs4hkkdlQFAplGYRZPekaXSo1XuqgfPsQZfteQB1SfGvDV0MIX+4pwdg67eoL5A5QBm7524Oa2A79BYK9Cgy5xGmhFmSUbcq22W33+3A17WlJMbcRWIr+k1M5oFSkYpzjDZvfB6A=,iv:mvZb8a7RYGdW+mqJ0tbVRjZdYMNeBOb0/mOWASsOU4g=,tag:lTNYWsUXDSkhHcc454Y1zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
