---
linux_desktop_bootstrap_admin_user: mmcnees
linux_desktop_bootstrap_authorized_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"

linux_mint_desktop_enable_cockpit: true
linux_mint_desktop_enable_host_monitoring: true
linux_mint_desktop_user: lmcnees
linux_mint_desktop_launchers: []

host_monitoring_enable_beszel: false
host_monitoring_node_exporter_listen: "0.0.0.0:9100"
