---
ansible_host: 10.0.30.183
ansible_user: mmcnees
ansible_become: true

signage_url: "https://questboard.home.mcnees.me"
signage_extra_chromium_flags:
  - --disable-gpu
  - --disable-gpu-compositing
  - --disable-accelerated-2d-canvas
signage_manage_network_stack: true
signage_wifi_interface: wlp1s0
signage_enable_host_monitoring: true
signage_enable_cockpit: true

host_monitoring_enable_beszel: false
host_monitoring_node_exporter_listen: "0.0.0.0:9100"
