apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.sops.yaml
  - job-prepare.yaml
  - deployment-web.yaml
  - deployment-worker.yaml
  - service.yaml
  - ingress.yaml
