apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-secrets
    namespace: hdf
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:pf1IwW82hMpP1uZ5M9+QV2NYuy6dboG7SWZ+MAgPc9cftFWEbz9lLbpWdj7HFfT3ErdsNqpSaNdSs10blQ9hM5NZ+xUlvhorHZNdenNOSjWr5h12HH1I/OrysYpsrxu7kuV9mGFkUEo84Lwfa82yI0DD1RvYL0tP91tQfHDlHOY=,iv:A0D38HPh4lSUqkfLn2A9gzDnEVePZx29eV3gKr5tWFk=,tag:DP7XGtU6+VYywPPdSakrOA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Bpxxyl3p+om7Omztyhks1Mb7RIPZjERMlGbYJoAgvQs=,iv:wB8a9C4vchFxXvQ+iSRT87pVL1PTtJgAyWEYY2TOBbE=,tag:zN3hOIvvdFZtjbjs7yljNA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:K4JG413JmJHpBGKrIZ0wLk0HFTsDkcWazjSBi+k0gVCy71wJ9SQOlJBaRYOOEs2UR/k0XG14y9xf8CT+C7liUPVhgVTBTgJ28XUJ/cZRJHqyoGuohdj+vXJhqKBQv/2dFYWIvoObbg==,iv:nr2or0MeQ0Bogk2fLuc9crvEtqp23l+WhvT8W5gOBEE=,tag:7Hw7sTO0vgOA1WgVGIna9Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sEP2RL03+0Q4iiUmmfs+v9HA+Ih06K6tFQLU05zEZjk=,iv:ETDYtS4M+Q8T6N1aMcFL3kK1NrjRdq01unJ6A20Di10=,tag:9t3WYw9P2KR+C39/2ol/JA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VuCYd6bGl7fV+MP4Pf3xv666lwS0e9maGhD/OlSeC0SBB5Ml52c+Q8yYpsIg5nh7,iv:S3a1XHskYa91D/byJoFK0iDkOoY3ZFVlOAjQsF86tf0=,tag:vmHFcoupc/OLRemlX15J4A==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eStwdFNHNTRvKzIrQmM4
            SXJQMnUxOTZNTW9LOTdjUVlDcUh5MCtnTFI0Ck54L0Rtb2pldGVwVkM5cTMxc2la
            TzBZOVF6eUIzZGliSWY5L2dNKzg3dlUKLS0tIGFsTU1LN1NZWHFCNTBUR2RaLzVu
            QVNkNm8zc2d0VGhLS3psTE95ckY4bkEKQZhjbWAIf156R7mLVX8FsD6vdnpacSe7
            uDylQrP9ZhPRS48/oQGgOVCaC3gChUMDGtDkhN1N0LfqihIje44QCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T02:41:18Z"
    mac: ENC[AES256_GCM,data:pEm3na/MkJz3UbdmGRXOuQRI38z7SZsIkSpVv+do1LDMA9Qn0I1BpUIWfK4oMOmktsplt5KkP2zvxX4lgIXxp1eSqezOP00mc0azbICfRlvtThXK4Omb7wDbynkjmYuswaERvjdo8fA7L26XFbuxDQXSnDJMX9ZhyU9YzloeNMo=,iv:r4Yz0WQOzdrMLuqlf7pbX7IPbdwsQ10NT4wl+b5nqaQ=,tag:Z52ZEiny6XdeQyjFotSMGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
