apiVersion: v1
kind: Secret
metadata:
    name: media-exporter-keys
    namespace: media
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:UxsOfEJjPJC8ODI0Ipl//zUFrLQ6wJqitgYSB/ZV0PU=,iv:h8VxQXVDAEPA0RKn1BCTfuh7BjvVpaQfi2iuVmHbeZI=,tag:8IIKnTMvcb70WXZkvDBSOg==,type:str]
    SONARR_ANIME_API_KEY: ENC[AES256_GCM,data:crUyUvJuIdgrtgCOXym6EmoWhKk8Q0xQHXy587Lon/A=,iv:HU0bupcbb6GY6SHmZwRYYHHyoQCPxJ5HkGEs7QA7+iM=,tag:7v+pBbrhwyuI/zUBn46IFQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:9qH089pVZ/oJgV+JTU+di0eGuW10Vt8ZAlF1GJKzgdc=,iv:SJMtiSgZzpC+7CMMu2tGXFp8ACLYUxeabsK3tTIfbpk=,tag:J7oZ6Hn0ZAMNH0Y0VGEuLA==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:yGt1rmCQpLxCj+U7nZiYGkNEe1BqKUYxFDWsJbOPZxc=,iv:+d4CP+ssW4FU65w4kMT22vcTGb6nbwuneIxnNeccXx0=,tag:Utl96D7z9e53Aq+vN0Am4Q==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:EkARelAJ6feCW9j78XtIG4VGc3SGOHVeCQbgDHEDvIw=,iv:qupM4bohvpq13UZqVXV7KhbH8NL60FnabI49FB/XXA4=,tag:KgloGhDoIjc6oy2aq/6Dzg==,type:str]
    LIDARR_KIDS_API_KEY: ENC[AES256_GCM,data:S1mwEGg/SwrXHWVQ+KG8VC3AmbybjlOR3Ztvh0rMk/o=,iv:UtdSeSH8mqjZeXd8wtsQDHFXMtIZhG2ozSvfGsEKmAg=,tag:KPCtE+0rE75OW/0bg53dVw==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:paZfg1CVn9Rod4dl6JTxNjNraWiTEcj2XtQf2/3Z8KQ=,iv:Ixymrj5jyxJ5LbGaLbuveuxqYnHcRpQW6fFiCawgKSg=,tag:DIJ/Tj7bAJRbTJFSYMRCuw==,type:str]
    TAUTULLI_API_KEY: ENC[AES256_GCM,data:L/Z3eTNDn4g4sLmoTmf4T+XfnEB97geDN/qfsUZwK14=,iv:HBTLiSdzShbF80jtvR2ZUYqX7hXRIjk2fDGazsPzRwA=,tag:Zn4Z4NvLF+gG4ulWl2kg9A==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSmt1RTVHbHJrbDZ1M2RK
            TnFmYmdKWnFUY3RoM1FHNHRMaEFCSTRCTFhJCktpVGF0VW5TTGJYVHovK2ViNEht
            b0tQV09BcWY4Q0tWMlJrYWZpYkF0OHMKLS0tIEJwcml1L3lLWFEwYUNhM0JCaXlp
            bXIydGpJK3JwK1ZZOFNMaDB4bHF5WUEKHD3cJ9DrRqIALciUy+dcwYsZ18CuSdTi
            NF03ss8k+kdUMdd0adQvjuFLldeS83vIUtFIuBCUwFBqRodEvkvKqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:15:45Z"
    mac: ENC[AES256_GCM,data:1KmfohxNn92X6n0DoVmt5/keNJIfM5SHTYb7WoFkjCLTzNlPpqlo/MbhVxbZr590ZcdACit7BXsuERj//EOZEbxxREpUcFQhv9YaRzzq224n5I7c0wZ2vuHmxQJkrAG6SU71aurTyEfGfzqc6uLneU3ItrC45vmhIpXq3AU+CFM=,iv:tiywKMwY5ApI6SZuDy8Szp3MCGLLZoVnMS8yEQMPu7A=,tag:IKolG8Gd9hq6LffNQw9WJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
