apiVersion: v1
kind: Service
metadata:
  name: adguard-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: adguard-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.0.18
    ports:
      - name: http
        port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard.home.mcnees.me`)
      kind: Rule
      services:
        - name: adguard-external
          port: 80
  tls:
    secretName: legacy-home-wildcard-tls
