apiVersion: v1
kind: Service
metadata:
  name: beszel-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: beszel-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.2.21
    ports:
      - name: http
        port: 8090
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: beszel
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`beszel.home.mcnees.me`)
      kind: Rule
      middlewares:
        - name: oauth2-proxy
          namespace: auth
      services:
        - name: beszel-external
          port: 8090
  tls:
    secretName: legacy-home-wildcard-tls
