apiVersion: v1
kind: Service
metadata:
  name: gitea-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 30008
      targetPort: 30008
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitea-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.1.1
    ports:
      - name: http
        port: 30008
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: apps
spec:
  entryPoints:
    - websecure-external
  routes:
    - match: Host(`git.mcnees.me`)
      kind: Rule
      middlewares:
        - name: public-chain
          namespace: infrastructure
      services:
        - name: gitea-external
          port: 30008
  tls:
    secretName: legacy-public-wildcard-tls
