apiVersion: v1
kind: Service
metadata:
  name: gramps-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gramps-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.1.40
    ports:
      - name: http
        port: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gramps
  namespace: apps
spec:
  entryPoints:
    - websecure-external
  routes:
    - match: Host(`family.mcnees.me`)
      kind: Rule
      middlewares:
        - name: public-chain
          namespace: infrastructure
      services:
        - name: gramps-external
          port: 5000
  tls:
    secretName: legacy-public-wildcard-tls
