apiVersion: v1
kind: Service
metadata:
  name: hass-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hass-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.0.60
    ports:
      - name: http
        port: 8123
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hass
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hass.home.mcnees.me`)
      kind: Rule
      services:
        - name: hass-external
          port: 8123
  tls:
    secretName: legacy-home-wildcard-tls
