apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homey-public
  namespace: apps
spec:
  entryPoints:
    - websecure-external
  routes:
    - match: Host(`homey.mcnees.me`)
      kind: Rule
      services:
        - name: homey-external
          port: 4859
  tls:
    secretName: legacy-public-wildcard-tls
