apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates.yaml
  - gitea.yaml
  - gramps.yaml
  - hass.yaml
  - n8n.yaml
  - outline.yaml
  - pelican.yaml
  - pelican-wings-public.yaml
  - portainer.yaml
  - pterodactyl.yaml
  - pterodactyl-wings.yaml
  - readarr.yaml
  - pxe-bulbasaur.yaml
  - pxe-charmander.yaml
  - pxe-mew.yaml
  - pxe-pikachu.yaml
  - pxe-squirtle.yaml
