apiVersion: v1
kind: Service
metadata:
  name: lldap-legacy-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 17170
      targetPort: 17170
---
apiVersion: v1
kind: Endpoints
metadata:
  name: lldap-legacy-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.0.19
    ports:
      - name: http
        port: 17170
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lldap-legacy
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`legacy-lldap.home.mcnees.me`)
      kind: Rule
      services:
        - name: lldap-legacy-external
          port: 17170
  tls:
    secretName: legacy-home-wildcard-tls
