apiVersion: v1
kind: Service
metadata:
  name: portainer-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: portainer-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.1.40
    ports:
      - name: http
        port: 9000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.home.mcnees.me`)
      kind: Rule
      middlewares:
        - name: oauth2-proxy
          namespace: auth
      services:
        - name: portainer-external
          port: 9000
  tls:
    secretName: legacy-home-wildcard-tls
