apiVersion: v1
kind: Service
metadata:
  name: tautulli-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 8181
      targetPort: 8181
---
apiVersion: v1
kind: Endpoints
metadata:
  name: tautulli-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.0.54
    ports:
      - name: http
        port: 8181
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tautulli
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tautulli.home.mcnees.me`)
      kind: Rule
      middlewares:
        - name: oauth2-proxy
          namespace: auth
      services:
        - name: tautulli-external
          port: 8181
  tls:
    secretName: legacy-home-wildcard-tls
