apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-external
  namespace: apps
spec:
  ports:
    - name: http
      port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: uptime-kuma-external
  namespace: apps
subsets:
  - addresses:
      - ip: 10.0.2.9
    ports:
      - name: http
        port: 3001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma
  namespace: apps
spec:
  entryPoints:
    - websecure-external
  routes:
    - match: Host(`uptime.mcnees.me`)
      kind: Rule
      middlewares:
        - name: oauth2-proxy
          namespace: auth
      services:
        - name: uptime-kuma-external
          port: 3001
  tls:
    secretName: legacy-public-wildcard-tls
