---
all:
  children:
    proxmox_hosts:
      hosts:
        latios:
          ansible_host: 10.0.3.196  # pve1
          ansible_user: root
        latias:
          ansible_host: 10.0.3.40  # pve2
          ansible_user: root
        rayquaza:
          ansible_host: 10.0.1.100  # pve3
          ansible_user: root

    # k3s-ansible collection expects 'server' and 'agent' group names
    k3s_cluster:
      children:
        server:
          hosts:
            articuno:
              ansible_host: 10.0.10.11
            zapdos:
              ansible_host: 10.0.10.12
            moltres:
              ansible_host: 10.0.10.13
        agent:
          hosts:
            lugia:
              ansible_host: 10.0.10.14
            ho-oh:
              ansible_host: 10.0.10.15
      vars:
        ansible_user: mcnees
        ansible_become: true

    postgresql:
      hosts:
        metagross:
          ansible_host: 10.0.10.90
          ansible_user: root

    mariadb_servers:
      hosts:
        mariadb:
          ansible_host: 10.0.10.91
          ansible_user: root

    storage:
      hosts:
        truenas:
          ansible_host: 10.0.1.1
          ansible_user: root
