apiVersion: v1
kind: Secret
metadata:
    name: mantle-secrets
    namespace: apps
type: Opaque
stringData:
    MANTLE_DATABASE_URL: ENC[AES256_GCM,data:ebUcwKror3FUgFmrPT39ilWMZ9Hco/cRol3yD6qEW25FHeogOCOiEYMtJ8X2LmkOUnjCmUtxc5E7EDLRdl9rITvKxHczpwbTrX7GggT913vOJPBenaW/lLHkFV/NLvFTKc20TyW5QLRkDMZbCd5K9APd/A==,iv:KPMJFunYeal2vjypbSrn+niK8WOgQ0G+Yob03GL/VFc=,tag:iaiWuk5N67o02t3qIM4lPw==,type:str]
    MANTLE_ENCRYPTION_KEY: ENC[AES256_GCM,data:mqU93936zM/RR8tLSi5noP5T+o7GzpbNqnXMl98PWAQLRXwKCStQ06UOlsFO8xVPga+8cmb3dJ2Ok073hnGzAg==,iv:c0pWxPkhk7zcN67QP7qWB6sj9GI1eiT2Iq2znKWi7C8=,tag:HJPsZdzK7qAgk+Oeph6l9Q==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeC9aM2M3aFArTUoyYlFP
            VDhsY3E0NlRJR29QSzB6ZFNLcjVha1hKVFdJCi9nQXFLUXcvMFU2K3hJSmlIVjRH
            MUtxT2Z3aHdJYzVlT2c0dWhpQnZUTVEKLS0tIE4wd29YWXI3T0Q2N2J6aTBYazlj
            RUgvRVBGeEJkdXR5T1FpKzl5RDdrcU0K6DDLbq9A127CGCFwTF1fPBUTYqVHCgA/
            KRW+FV1sCuSWCapijL8HxfpNB0CfnvApRYqEbWdwa3NMH+assf7FUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T04:06:08Z"
    mac: ENC[AES256_GCM,data:A4VKqKSNk00De402/Khwmv6E+jWdG2qUnGQ3C0FjsB+tF48viDBgRe+vuFHcQuC8AM++df9ku3rJyqVxJ4hZPC36LpN2WataZc1WanvHCGojh+euakFbr9v+xwtcs0CX+WsyGIMLGl/SD3HlAX0WgbnBI9NDr9QbAIdUiHa89Yo=,iv:fdvS2tyOXVsbARTtDqNDfQYBboHspx2WJGcNozynalA=,tag:A7nwPg2LeNtxApNlnGL5aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
