apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: local-path-provisioner
      version: "0.0.36"
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    storageClass:
      name: local-path
      defaultClass: false
      defaultVolumeType: hostPath
      reclaimPolicy: Retain
      volumeBindingMode: WaitForFirstConsumer
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/local-path-provisioner
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
