apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-media
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - noatime
  claimRef:
    namespace: apps
    name: paperless-media
  nfs:
    server: 10.0.1.1
    path: /mnt/data/k8s/apps/paperless/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: paperless-media
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - noatime
  claimRef:
    namespace: apps
    name: paperless-consume
  nfs:
    server: 10.0.1.1
    path: /mnt/data/k8s/apps/paperless/consume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: paperless-consume
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-export
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - noatime
  claimRef:
    namespace: apps
    name: paperless-export
  nfs:
    server: 10.0.1.1
    path: /mnt/data/k8s/apps/paperless/export
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: paperless-export
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
