apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-secrets
    namespace: apps
type: Opaque
stringData:
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:77QOGb4+U6l0,iv:uquV5y9Nmm2tcYL9b41Xj7Reno02xHz8r/gJ6+Gxyw0=,tag:lg7qhkX0BNQMFseRpieVfw==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:Iu92aDhQp3AhaEAmpe4IPkeRGCtSAN3DDzVQI1tl6eI=,iv:qoJaZybWEPFlgQpqsB3veW1NBnnEJtuGXzUjOmPihIc=,tag:o8vgWRq0NgS2iX2DEpUEmA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:vUW2c5TshrcXUtw7ERIJucjJErE3K7jKx+toPfQzEw4KhV+70CWkDeg7D4Wk0ANnz8+CwN6cB8v6r9srxd5YRQ==,iv:VQ2Tv+9lsOIBmEJhQEk0bUjmfKcvcTVwEtbrXaN+R/A=,tag:6gMgJ92XOJU2Z8GkHa3o6A==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:z1nMsy4=,iv:lB3tYbqNf1Zf6MTJkZjgMsLufWV3yYLAUkkqZaXL75k=,tag:xqL21oFWLhNacvYm+48NLA==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:9RZrSP1sbaw4Rdl84Ww=,iv:0rVZ1QiIhZZHiTcoLpPNc8RcVsRLUa2qW0pwus4HboA=,tag:qemK4sGKfYEZixNmVaGFHw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BYf9iQ4k2SIdcbVLcBwm1a0RkSDf3Dl4SZRZvMOgq5E=,iv:dAj30wWHQhgGAZUCwQxlbdYG6HF+rDlkZ50QRD/zp2Y=,tag:DfpmjPw7DNW3Hs7ZEEuHRQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZFlGNTJDMVh0anFFeXJz
            ckRXZHdlTWRXVmd4TzVKandlT0N2YmFkckJvCkx3Ty82aVpNWU5iWDdrRjZUdGZK
            SkxRckdkQlg2TGN0NVQybHhBd0h4Q0EKLS0tIEtJSCtRMTlkRm54QnN0SU9kaGRN
            TlUvNlVzNjJORnhUVW41bWt2ZmlNSzgK4BYXx2airIQzI8rXtwWi23R3BjE1g28O
            dxC4JMX7fQxCsPZYHBVc/OQxJNj96YAQkqhS38XHCjwT3dfz41hcvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T02:41:27Z"
    mac: ENC[AES256_GCM,data:gWftE7Mqwvcgkfx4gX+mfdmXQYj0lltXeN2N+U1g+jfGdCvDnbAOSmQ3kIVY7O4K9DDGmIa+lvDqoP/O33VRqr++TDK5kTYGSugUrtEXqWFYHYvfLo83ctFWgHjpSP5vl/DjtAp4EaDktBUYIndpxwb5Opmj2etBTRYGpUzImSg=,iv:i3t2HxvS5eU5lpC1vs6IhViL0Nk9YDdRfyNQEF1SErU=,tag:/e2CRnCWuZwYWlJa7vW/fQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
