apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth2-proxy-stash
  namespace: auth
spec:
  secretName: legacy-home-wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - '*.home.mcnees.me'
