apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: storage
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:wjAS9OttLIXq9aJC4og=,iv:y7gJyvoVmNMm16hEB2P5LrgcU2fDwq45N7tXV7KrP5g=,tag:/1klIf+CmacaE2yqYNZ3fg==,type:str]
    userKey: ENC[AES256_GCM,data:QQs0HHTliHkOtFnVarpL2J5Mz3GlyQiG68702ew1GH/yRF3JHU9PwQ==,iv:39hq50v7tP5XR8i+JQEM3iCn4AWlYPs30d+p1ohnqPk=,tag:UNAxI6H9Dp+m3ZFRdK1ulQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U2h4a2crRjdKdUViV1pU
            eGFlYUluaFk5akFoOFBMZFFhMGZzNjYrWkZvCm1nUEc3dEtUMzB3Zm9kRjV6bGls
            dkNjQnhESXFZL1N4RkZjeG5YYUNmbjAKLS0tIDN5RFdEaDBRNE1OZzNlb0dWd2tS
            Z3AxcndGeFltTjlzYnVHNWdLOU91OVkK0WKNx73bKS9LKtqjl9gwkSUckQOZAmXr
            rKsrMonHhsvCX3GLwo8rMtLDdqVqe4KPpqrboZ2+f2/ACksUB90sMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T03:52:59Z"
    mac: ENC[AES256_GCM,data:kHfGKO2pEKbrlBaIzFzMwv7zVur+mIjTrkD4mMyfXTgtNv8z6CaEKB+BMRccNvPe3EEDPkjeOnEwPHzWoAUcNo15wD5sxPJKeJ0IJW8B4Hg2wuq+Ar/8+4C4C5PPBev8o/bwiVOjRsaDWQC7BVxbnYbKBcVypRPIOVFPLaREvkM=,iv:zzkCtqAHxKXNbkIy9kGGHrJ/bQaINiQG7GwaLeMTJrQ=,tag:eqv0NS8ftdyf5T+tcQyzcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: storage
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:jbFgjEZqaU+2VAZOqZDXoao=,iv:0vhEBkYMTxNtaR9k3lku91ZROkNRQSqHaXl8U7z0uyY=,tag:+M/y68LZo4/eNQEe0/RX+Q==,type:str]
    userKey: ENC[AES256_GCM,data:JmhA4PR/uZXPBrhr9m06vxyEvKMUfQh+blE+9D0obOVom5voUNk2Ww==,iv:IerhsHgOJHpPkNMkOfwrSX4S3L+AZhOFd10eRC5HVx8=,tag:rV0L/awF5NojMMLpp363GQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U2h4a2crRjdKdUViV1pU
            eGFlYUluaFk5akFoOFBMZFFhMGZzNjYrWkZvCm1nUEc3dEtUMzB3Zm9kRjV6bGls
            dkNjQnhESXFZL1N4RkZjeG5YYUNmbjAKLS0tIDN5RFdEaDBRNE1OZzNlb0dWd2tS
            Z3AxcndGeFltTjlzYnVHNWdLOU91OVkK0WKNx73bKS9LKtqjl9gwkSUckQOZAmXr
            rKsrMonHhsvCX3GLwo8rMtLDdqVqe4KPpqrboZ2+f2/ACksUB90sMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T03:52:59Z"
    mac: ENC[AES256_GCM,data:kHfGKO2pEKbrlBaIzFzMwv7zVur+mIjTrkD4mMyfXTgtNv8z6CaEKB+BMRccNvPe3EEDPkjeOnEwPHzWoAUcNo15wD5sxPJKeJ0IJW8B4Hg2wuq+Ar/8+4C4C5PPBev8o/bwiVOjRsaDWQC7BVxbnYbKBcVypRPIOVFPLaREvkM=,iv:zzkCtqAHxKXNbkIy9kGGHrJ/bQaINiQG7GwaLeMTJrQ=,tag:eqv0NS8ftdyf5T+tcQyzcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
