apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: internal
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
