apiVersion: v1
kind: Secret
metadata:
    name: sonarr-anime-secrets
    namespace: media
type: Opaque
stringData:
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:nhH3AMtvle+HZM4e/jk+D17aYCSXvyofB2dEY1BtPdw=,iv:gafZJAugUdUxa+NvINEWBx72t65s74ZvIPIpt+/9Lv4=,tag:IdsNO+T15VmB9NQPeNY5lg==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvckdTc205MHhEQkhyK2Zn
            eFpzSUY1TGFCcnpHL1RZY2FWZWVUVWJSV0hjClljQklBbWtyT2czTHlTd0ZvY1ZQ
            NGg2YUJkc2Vqc2RKckRxcEkwNHJJcFEKLS0tIENnUXNoWENIT3Nod2xuWFlxTHlr
            cHo1K1BUOGpJK3NsU1RrL0liN0RQbE0KR/1+wJi8aFgJnLX2QhtpdEMkDwfK8T2+
            8TViNeaGJRCKdjbqkQbznFXpgF3/dFtdmGWzoIULrUdQe5/l6LJ1CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T22:49:31Z"
    mac: ENC[AES256_GCM,data:H74VgIhZ7ot2cWxGQcv8AivNccDdWPnaOwQGN6fuQGUe0I4UaFME1Vzlu/x/sBUvVKBDdL8SkbJr7JvjRwi8zbSZ2pM1Ap14SoWfXGdbbJ/yAApErjV4qcKx8mWKRq3dwTsHNengzZ6Nwzu2Anzu1FUSHXcMUFhRm6rH4LKmfCY=,iv:Xjue39H3uSF7faw06K+7bx2RPxfIILk1bdPYHbY8JGQ=,tag:ZlJXDdOLWfELAUehCaT5XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
