apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homey-data
  namespace: smart-home
  labels:
    app.kubernetes.io/name: homey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
