apiVersion: v1
data:
    id_ed25519: ENC[AES256_GCM,data:PMciAg9iv2uWvoyaIifiS3A2fMILhIybT66w67Rjp9TlCCrvqcn7hiKGpT4HTgVQT5rb69X36PcQbD0rDkQbS9xbVvw78NsW4xzN2fcT4OsisWw3c5sN0i63NhXCcFPTDf4wSd9iOsU5xFzrv9BuInYo6YREY3DWx5HVJaUH6g5rrWYMIZf9PGhxY3kGL19TCCtJEnnTb+FT/KW6mc4lObTkANyEqsK4LE0VgCFh25UfF2wb0lasImW/YCtFocWmzctY7pd/xKoIOulePElgNPa+kWEed99ZS9ohbQhWBf2ZlXDKrMuZyHBYFUu4Xo4hdMntUPFypWwkhvv9/b4C+zeg+mAs+LxPOGOHO3ahNHrTHwnMJG3I3hADa2r1wLNd4nP6AhNdoah6DAufdLcp99ReSMzJZsiTZsCkkMuT7Ab1DoNbqmF9ThjLTLrqx6y81N/rrQuncYywSdXYtunbs8wmy+KF4woxWQc7PB7/nqQYuJUUCh7Y2qdNdNNO/K5Kg5nbRudAUQjUy/u3ex1Gwk7ZqcI8aQc0ruYgO2F7ZpTLHlm+EUYpXmVjHXC2c7gKw+o/k7q4H0w8mTV5H7ZRah/zw8c9k+crqaMfNt2M6apY54pvdc5wKx8cpr0x+D7tQSHpxnsSpsNJjMlxUBMNHNv2CoyBVlH11LE6Tj2XPFRoRQX2XPCVErcZZw1gVgROTFHcaxBOUXdMTyr41/vCzlyPIyI3wYSyClvHgditlNU=,iv:qaeV5N0uDMzqcBaDreGvFWOuPWiR8GntHBxckQOIivo=,tag:ypooZPhU8LoGAy9vBdCXNg==,type:str]
    known_hosts: ENC[AES256_GCM,data:St3qqmZ3kWOR+T4qc7YN29kuA6zGsOqToyju0K2azeQdfOQ7KWiHrxuns2tYcG+fAd4qVAJgGpSANyQCtumzcRgmhFd7Mr6ioFSDICeCu66t8gdT58qs9lZdONgM1S71rV5WRW/u1a3jvUkL7O+jLjaDnVI72D+j,iv:DlNE7ZJC6RRMLtBxDPRjKvIxCsygi6b9fj1A7tARWwc=,tag:pCXfl9kOFGcmeL1XE1b3iw==,type:str]
kind: Secret
metadata:
    name: postgresql-logical-backup-ssh
    namespace: internal
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaytoWVdXeW5vNGlxaVM3
            R3ZtcUpFOWZZN1puV0dSejY5TjhsUXZSR1VvCm8xbWpsY0JaSU84YkdJR2F2T04w
            ZTY2WUhtYnU0SjN1cVd1UUxwRmlzaHMKLS0tIDliWTZ4US9jWmswNGpIRGlsNWFL
            M0JYK1Z3RllyYzNmTTIrK1RId2tmWmsKJh/iDcWQMNxYEzNISZ1xII69iHmxeq3E
            YC/bpVx9bRlT6+2/7iMSITCA4vAUtSGRgIfPWF1vW6cf/ThD3vcoYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T01:09:52Z"
    mac: ENC[AES256_GCM,data:biwt1JPGaTjosdwouZ7uJCZYy516SxpqKwroG9sT3rft3R7Vys/lneG3cK69HMwBtHDO7XGqRIG4ywB5XFjeHceQqXeoHwcayAXcjvNVFrTs64H7S1piRc9or55TQoW59bNtcimFm//5gnbuaSPY4J4r1tIUdYKSzH5NFXwRsxw=,iv:n7G6WoVdlHwaf4DiAWmMvfTFC7lpgGhnqHafZKsQ8Uo=,tag:1qNedyAwethxulvT8uLxyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
