apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-logical-backups
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - noatime
  claimRef:
    namespace: internal
    name: postgresql-logical-backups
  nfs:
    server: 10.0.1.1
    path: /mnt/data/backups/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-logical-backups
  namespace: internal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: postgresql-logical-backups
  resources:
    requests:
      storage: 100Gi
