apiVersion: v1
kind: Service
metadata:
  name: postgresql-backup-metrics
  namespace: internal
  labels:
    app.kubernetes.io/name: postgresql-backup-metrics
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgresql-backup-metrics
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
