apiVersion: v1
kind: Secret
metadata:
    name: postgres-exporter
    namespace: internal
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:BFS7M5Ep75rdQRnsfes0Jao=,iv:qn1JSb8L1SZNOzSb1h2Xhr6t8mjYn9x0uSWYDHGuOeQ=,tag:IiQwoMMY5r7FMX+iAuXK4w==,type:str]
    password: ENC[AES256_GCM,data:HBwS/FCSF22n8eMWie2sXCQagFovbxxtL+1STI/+crA=,iv:Cb5MT5S8S1YILWZAeUlNUmOm3MMkodRUOVRdW5EuXYc=,tag:eLQNORiunS8kCdUiLlak3w==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRStwemJ4ZVpRTU5kays2
            SEhEYXBKaU9PTVJPUkNjVldYbWJvSmlaaWpvCkM2ZlF6Q2FMYU16eHVTTEFJczRi
            cWtka2o0OXozRDBGaENYb3htaFF6UkkKLS0tIDVYVXZFU0tab1NaUExEci9MQlJn
            MXdzZCt1bG0rVDJUeTZLL1lnaTA2dWMKoHXPPUBJd78SS2N4Vl+qGSDKLVp1xf3j
            UU6GWXaF+O/YJtcrRGNJ6ig5ryNVMRD/iplTZJqBoY8zFrAXEKL/eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T01:46:22Z"
    mac: ENC[AES256_GCM,data:Vdf9tVUzYmtoHX0PVbKcd85opUEbZ2bdFu9iYA+fpPdB/j/8nVoL67qYgEt441dxm1ghlA2NQsSKInVhhsjmSX3e9nwSIhyYJ58HTql4YWmaGmOjzxeTPOIALAL+CLOaUglHdEfgqNDVzgUqLdWaY9QHhikX5b6Y5WR7t/UsN7s=,iv:W0yEt9r2396F+Vs4QZU16yMxkTMFAReSOpNaixsNDvk=,tag:fDxgjgjufwPuwtbHkkkXPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
