apiVersion: v1
kind: Service
metadata:
  name: metagross
  namespace: internal
  labels:
    app.kubernetes.io/name: metagross
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
