apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - grafana.yaml
  - local-path-provisioner.yaml
  - metallb.yaml
  - prometheus-community.yaml
  - traefik.yaml
