apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: auth
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:56AzTutVyF1xqPgdTnk1cNkFKIKe7YPy+gymshC/JIDFAMh0,iv:y9n4+A3cn/Y1ipdahN5029ErLIjQNYy9zccuQZbj5bE=,tag:eTkK3FdvNd/GNhOxmUQK3A==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:N5346HByw4GkAdJ+TdHeYvRemL2bcJglrr/WYcAepHg=,iv:NmvpFRXwKJCk3tdXfv3+iuspgD1DPQgYA1LDEuym144=,tag:LSUbM2WTiA4Ry98C5Ag+3g==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:BL0JKNLZ4OW2OehY0QkAaoCFsd3tDOo4XMn02j1XJL4=,iv:0rb9XesuqQpbIcsiCkAe0dK25OyQP+jUus1weEw+bVo=,tag:6vNEnMFlgUFrNPLo4ah9gw==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWdvSVl6NTd1YjYxV0ZU
            eC93YmlBTkNwdHRpbS9QT1pQUlpiTmxDaXdrCmZxQ2h5M05SVEVRUWFac0lMTDhw
            OWFMNmRIdFF6by9vM3JhMCs2OC8ycnMKLS0tIHNPN3prbXFsUFFZTXhVRXo5cmR3
            NGpPdWhUblBqYW9GYTFKTUEwNmw3L1EKyTeE3bincCc9vEAlCF+/r1cjNWDv1oXo
            0wPCe7Hes5KDlBNU9YuGUZ7GEeVfQCUwzxmPQh4rW8z8EfrEJqTf1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T02:06:27Z"
    mac: ENC[AES256_GCM,data:cbkbKsDUhTtE4S82bj6vdrK2jwGP+00oH6yLYzds4DCSW1yokSD5TdyNI2UI/NuWlsFQHCR/ixror8ThhvOSHeccip0/rozERsiGSGklA5AOoG32R6016P/fdqRapBe7effx2W12WUomp6a74fNeOqriNmKtNvOz5wRH3PzIK7Q=,iv:ckImBlwp9ZfMH9DdLXKT76+pC336sbdfu9U4K6FPm/A=,tag:lnBj5VT9qL20IFekEmW0xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
