apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: auth
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:Me6z85zYHVejlrjSHexaqTz7CY+iGVeuJ3LKplcAffsBxWWi,iv:N22wU65AC3Y7+qQhQFiZ2W1pskDz05JU3V9N8XvZcno=,tag:1lVHCqW9FOVrcV/c5MQfjg==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:CwLzBuV20BefprrX4Bu+dVgdQ8sJJgXrzUGGOO006XY=,iv:uDoVWRJmHNhhDHfNIWrS6CNlFtQHXieGpTY3hXYzJ8s=,tag:McL7p9xdauqMpczklZEd0w==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:BL0JKNLZ4OW2OehY0QkAaoCFsd3tDOo4XMn02j1XJL4=,iv:0rb9XesuqQpbIcsiCkAe0dK25OyQP+jUus1weEw+bVo=,tag:6vNEnMFlgUFrNPLo4ah9gw==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWdvSVl6NTd1YjYxV0ZU
            eC93YmlBTkNwdHRpbS9QT1pQUlpiTmxDaXdrCmZxQ2h5M05SVEVRUWFac0lMTDhw
            OWFMNmRIdFF6by9vM3JhMCs2OC8ycnMKLS0tIHNPN3prbXFsUFFZTXhVRXo5cmR3
            NGpPdWhUblBqYW9GYTFKTUEwNmw3L1EKyTeE3bincCc9vEAlCF+/r1cjNWDv1oXo
            0wPCe7Hes5KDlBNU9YuGUZ7GEeVfQCUwzxmPQh4rW8z8EfrEJqTf1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T22:38:05Z"
    mac: ENC[AES256_GCM,data:8OiT6U3qSWlQXtpgA7rrLJO+BEXMOhL/IW7CMYcO9OWgq+aynlhY9+PbksoyEDw5s7BhncvcqP6BmiAtIfw/btGgjGAlsFPjB9XEP9xV6KGNhNZOC1403Nd7MqbCBq5CNqr3+7MEG8O2z+Jll7Ji/vQ7f7sLaYbF9Vc95k3/fpc=,iv:wdfcE8aQIoQGI5gcqYLC1L/Fc5PHhEV5KmSI1+BR5mE=,tag:63D6lLiJtdTXtFD2P2rZcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
