apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: apps
stringData:
    OPENROUTER_API_KEY: ""
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    XAI_API_KEY: ""
    OLLAMA_API_KEY: ""
    TELEGRAM_BOT_TOKEN: ""
    TELEGRAM_ALLOWED_USERS: ""
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VnV4QUhjN1daTkRhdVR1
            aW1CNlEvaWZGLy8vekJNVDBtSmVTejF1R1FFClNPR3VvQ2dTVStCNUkwTjZkaDNB
            TWhpbG5OakpBdFlxN0hvcEZuWU1oVTQKLS0tIDJMdlgrdW9MUk1CR3c0eXFSalNK
            ZUtKQnZXSitPdTI3TVlnRmx5cjJpV2MKMonWLs5tjG6LGv3K1TnuCwwGb/eu0wNZ
            jx6RvY9v7wMcc0vJlCbxYz6IpXGS486BwJK8T+vhNqByQSxlT29j/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T02:24:47Z"
    mac: ENC[AES256_GCM,data:ftz2zLW8DUuWex0NFQgCNFbIgNNEo3dZSQkhHDGzs3+Y0cnVK+EKKt41rSiUqtDDf72MgLpjxESCTVjUquapv+LA4SduItldlBv2OzeCjPHw7/XX+DYWAEJMb/BIJK0oDyu+QBdoet6/iqO20Yjscy8yNsYNFpHbcwfBL94SN8U=,iv:2u+Ol/hcUAsIMxczYFt3/VcFsRh2D+0XwpRuhJxFMow=,tag:LamYT6cJL/TN1o7t79iCSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
