apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: apps
stringData:
    OPENROUTER_API_KEY: ""
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    XAI_API_KEY: ""
    OLLAMA_API_KEY: ""
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:XIC6dL8h38KxQunL0YS5YniwO9atVgHPDapDFnBCVcLcLEKhkMlZdBSWWlXMjw==,iv:UaCMrnNJ3D8Sh70WPpS8NI3VMNt8lleoBMd/D5om9Xc=,tag:rct5xgLFje/M0gm4ATRCUw==,type:str]
    APPLE_APP_PASSWORD: ENC[AES256_GCM,data:v5+BMqU0tGyOfM0GksEO3rjeww==,iv:C4NdVTFqxiio5WIA4ensODBAiM7TsJVgzryHcB2ygrc=,tag:T8FPrEg8F+oKy/W23yxNeQ==,type:str]
    GMAIL_APP_PASSWORD: ENC[AES256_GCM,data:/oRQNWKtfpdky27M/3BeqMP5hQ==,iv:pikP7FujpWn7B0M0DR9PY2Tg7oF9CmLPU52YZpey02A=,tag:BZAcSqO/r+bfWvSQ8VzuFg==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:S8+FzGg9G3mGxA==,iv:ZadxKup3v40atQaPjesTPV00jdxX4V+Qslpk+q4Q4bs=,tag:GI28S9eADjTin8cEDXWUKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa0J4Ym5GRmR1Q01SbDRH
            OENWY2MxNG9Ub2FJWjVsUjF4d0hCQVFuU2hFCmxVMzdPdmVJb05oOEUrQnZxbkVH
            VlpBQVprTkdQODg5bnhHeTFPdk1UWWcKLS0tIDVZOGNRTjZqZmt1ZFpRNUJvSU1U
            UFQ3bytmdmEvdElrUXl5bEZRZXJRUk0KzbKAIyROzMGbTNVdjL7tX6q36vx3zaJE
            ksqD1MSkdzdwGZqokMcg+68DdEc7h03Aa2KzBlQYWvVVytGBA6ofDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T16:43:34Z"
    mac: ENC[AES256_GCM,data:YuKx3GfFQWzUXY3UIueT6HvmfhQp/izpdsJ3zrY9oR1nLtdRpaie+Po//iHQ8FLuXfYX4T3BpPiku2igdLaLrg4CrYc9NMeqcZv8cBZVRsKLsKElJauM1Rd04XlUuWgAWVw4EpqOvL+iEQvbWmme7QUNw9CVLKWDm+NkQWR35HM=,iv:LUWBfyFvpph5iKx0ydjH1CL9h2rwuGnoXZdXY3tsYuA=,tag:BWoIbWQIVJ98VS+6n15vcQ==,type:str]
    version: 3.13.1
