apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: apps
stringData:
    OPENROUTER_API_KEY: ""
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    XAI_API_KEY: ""
    OLLAMA_API_KEY: ""
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:ZC+F8Ey73otsEs7UOpK8VNGzfulS7pH/AgQ/oaemcjDlp+R95+1eSbocjHuArw==,iv:jHX2i2HPpU8HfaEJ5y7OrONMtwsva16Opbuc31+PS4Y=,tag:nW7mvl7FFkwUGrjoj3mPPg==,type:str]
    APPLE_APP_PASSWORD: ENC[AES256_GCM,data:DAHYQpdSonGtnLydJcaN5GXYaA==,iv:LB8e1HFvnF7wKZoSMf3pWVhQelrbb2UorNsiziKQI6E=,tag:+EqUB/kt0zA/uk1bPEXhEA==,type:str]
    GMAIL_APP_PASSWORD: ENC[AES256_GCM,data:sRWta4UEYFOognizc6iuey14sg==,iv:Dl4Ra0ErB8cO6yBrEfU2nEuuhEFoSamrFS5uhkn6hKk=,tag:nY2bnTUEBEs1e3D6VsSrQg==,type:str]
    TODOIST_API_TOKEN: ENC[AES256_GCM,data:ltdh9vB/dvWNQ4qAXllothE91tGEbegKvTPiY0/zlvhyuNStqCOz3A==,iv:2EnQi8CbnhK94d9QKzboXPBY7k+qJA85c8cieQwJGk4=,tag:BDYIoCbxq7b6Vau8yIrZ8Q==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:VwD+RL5elBPoww==,iv:g9F8YCG/dMACNM3ESHs2HuI+0olklEBCYXNOiPveas0=,tag:hmubwJPGA6mgWdeHzC6h5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVjdZS0dnRnY3MjRIR3Vs
            bzVWTTY2WTBKcnJsQ2VycFV1c2ZucFRPS1hnClM3STA1aDM5SmtQSC9BQTJXTjB6
            OWgrcVpQVXIxdThTVjg4VEJteXgwTWcKLS0tIHB1T2RXeDlXOWh4YVJWTHB4Wm02
            M0Y4T29iVlI1c1NFcU0vS3kxRlY2bHMKqlRLBMkrbcvamfv6ikEkBLEfavckhOrX
            Cid7VEVmDqnkQzjyAwEf/yIy0Jq3/b/ln5KhgoKaEZoc4NgsUOG0/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T18:38:32Z"
    mac: ENC[AES256_GCM,data:ykD66np0LmSCGqkAk7DR54OuB36VgzMK8DODWSd+8E3BGCDLx6af5s+xrWjgxQLw8uoUN0c93fFQ8i0XPSf2j2SgvA641+98FvbfZJiCW46BfZFB6ybYlm4kpJICss2aVgwVBDADD6KxTvGmJQoAJY6iBXwHgUJeSBrbWx9zOMo=,iv:B/DKxKvDfqjVudjt6s+v/JEW7EZHpb5h/grEpOBw7Ro=,tag:5p0c97jzjayhsyoDLoY0VQ==,type:str]
    version: 3.13.1
