apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secrets
    namespace: media
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vCFGuTCKvw3G+/cgV++jMoLxOhgg9g8ET9DoJasWxqQ=,iv:bJR2KLF6yr0yESAFElN7W5G1ggzgJmDXsErdzD+dL9Q=,tag:c888kcUsL7lO3r4x0O3ugw==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRjlMczVlT1Y5NEoxeDc0
            M1ZZUHFwUmt0amFMMERkeHJIblVMaEczaFZNCmJQcFdLS0VGTmdLTXZVZzh2Wndl
            TnBvaExQajJwTTBPM3VLWnZiWG52Vk0KLS0tIHBsNUlHRzRDRU9yRk9GS21mZzF2
            WW9NTlhDWkZmazFuTUFIQWQrWENLUDQKizRLMWD4kmIvt4xhyYtku7eca3Xwpzwq
            nQ+v1UfW/4exhe0k8EwYSLB9iZwVZanMEksOEvu7F1Deodgc3wuQJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T22:49:31Z"
    mac: ENC[AES256_GCM,data:BOTrp3dhiGSkCZavI4REt9aAp6aKc1r53jFEgSki4+mQWFa8Tfs0gJqDOtcr0ySsJvJ6nTCnv+LsXtVkbxT5QhZCn8frnYvF7IFBFs50c+oGDVsax8hwLD0YYv5uUviRTQhvK9Ktxa4yasdTE60UNAxrH7VrIGSJ7sFwMQJhrxw=,iv:x1w6YOXdJNvT0IQjU/OyRYIH7omjna3NNtCy7YMJU4o=,tag:35aS4+pu0IYqCQDoIxEagw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
