apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - shared-media-pv.yaml
  - ./sonarr
  - ./sonarr-anime
  - ./radarr
  - ./prowlarr
  - ./romm
  - ./lidarr
  - ./lidarr-kids
  - ./bazarr
  - ./lazylibrarian
  - ./tautulli
  - ./overseerr
  - ./wizarr
