apiVersion: v1
kind: Secret
metadata:
    name: paperless-ai-next-secrets
    namespace: apps
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:yc3+SDbdpwnWdkfGwmwr62eOA094RCQK4vNY8dUF/02qdfs2x68dFH1di2JDNEDkJjucVVxL1u6Z9wqW1hF1lA==,iv:x3aWDi6YAYHWXw6IGVoodsEfE1AZolpdvXkZRAVwZrg=,tag:U892Aob0muM+RkxTMQsDoA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:dUhJ6lpXeFYCQTKv/gKPZd9iBfzlcKuI9LH/5ScxEdEkqDTB7SmI4rISD0lQZVGCwM2TlgO/9fK2f2OIWWf2Lw==,iv:aJ4BevoCLeOzu+1At84winGgEDUDAzNf2Ipx7yRDK3s=,tag:SHUyktIkPqnpz/cF6qgeEg==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubXNxcmRmUWlGOUpXRWpw
            OWJKaFNvM3MrMFhoR1pNTG8weU5wd3Z6VURZCjlIb2FLdTNFMCtMMWNlNmZuMG1P
            U3RZa3VIcm9tVmVrb0xKb0ZjV1c0akEKLS0tIE9yRFFHUC9pQVlqSkM1c25ZdUJz
            Z2h0QzZONnJKc28rSlJuZG5iU0xTWkEK+Bq445HMCgWO4soD0hmwtzrKz3LwPW90
            ce22hnwuOv++QhD1aX7bQ0Fjyb8kp5ypFqilXGLsj7UyVJnxYxavug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T03:24:19Z"
    mac: ENC[AES256_GCM,data:s2ZaAxxho0zFSk1NRNCtBzYPZFpY2psQDjfVAWWl2C6oyxOpijbw5gKfmQwvSxlZQnlh0nCgK4ga0hV041/pA92dCB1xdsX1rDFw3QFp8GXdPsVqQwMB7MoGJp2L3+5vwLcP2RUZE32wO5ov6EpPILHGnNzRH7Fej5wn9W1NJO4=,iv:p6sEgn5iG8dsjfDsFGU8R8f1pVhHLfe8Y7LNFJLHzAk=,tag:q4ToddwcUXu5ABrZrlXkUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
