apiVersion: v1
kind: Service
metadata:
  name: paperless-ai-next
  namespace: apps
  labels:
    app.kubernetes.io/name: paperless-ai-next
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: paperless-ai-next
