apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps.yaml
- auth.yaml
- backups.yaml
- databases.yaml
- flux-instance.yaml
- flux-operator.yaml
- hdf.yaml
- infrastructure-configs.yaml
- infrastructure.yaml
- media.yaml
- observability.yaml
- smart-home.yaml
- storage.yaml
