apiVersion: v1
kind: Secret
metadata:
    name: webtrees-secrets
    namespace: apps
type: Opaque
stringData:
    DB_PASS: ENC[AES256_GCM,data:2sRtuOlDjR/2yUp3R7Ir2EOJlaak5plsiFPkxWWFPZfghE2OJHGfSaP8Cps=,iv:tgMxUs9l0TC3JMv4w1EwGaKMxXd4zZFTz3PRK9M0zkA=,tag:AyWQxj9wWzCM/3UNtTofPA==,type:str]
    WT_PASS: ENC[AES256_GCM,data:DgIPCgKsZlwB2jQ40FbLEcp4pJ/1daNim8IX7R3t/oI=,iv:L8Eg/WsCEdDDs5utHbhMK0XFTjXC1eWK0P42+07lp1M=,tag:Cq8tVt4CPJWIldDo08IN/g==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M2gzelN4eEptV0hLTHdp
            Z3htWnEvcnVwNmRXNU1mRkpzc3Q5SUNEbDJ3CmtpQzVWbG9TVis3cEYrK3lZb3h4
            VTRELzBzVzJoVE5lK2QzN0VNMUQzU0kKLS0tIE5jSC9nYzJrcVcvSWljTFMyS29M
            bkh3NGliWEdma1kyUnlpV2R4eHQ1OGcKjDDaC0IACG8ACWX/R9YQJZxjgkAwiuXe
            Picyq1Frb+F5KMnK/iIbDI3q6aAmC/MXv7DTMYR5/61a4wEKPGQ/jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T18:16:10Z"
    mac: ENC[AES256_GCM,data:Oqrm4ep1vbZIikIjmi7QiK5HemJvx2tCkn1jmOISWCFqcdGisox2+tPYRF5+LpCXx32YiEBpD5z6oEb5kRfogrzubDjArRn5bafhm8Hmb0LPDoatzusN1hbFlhZoKW6SCnLAnBrhhnZsMcB0DQRnqWjz+vFdO5HpvA7u4n6JvjQ=,iv:EYkM6yPB4gu+i3yr3m9SIWhaqOkXqGlcb6g1ArC7MaY=,tag:JKr2/wj9nSSPnx7uJY79bQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
