apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
  namespace: apps
  labels:
    app.kubernetes.io/name: outline
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: outline
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: outline
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.37.0
          command:
            - sh
            - -c
            - until nc -z metagross.internal.svc.cluster.local 5432; do sleep 3; done
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - name: wait-for-redis
          image: busybox:1.37.0
          command:
            - sh
            - -c
            - until nc -z redis-master.databases.svc.cluster.local 6379; do sleep 3; done
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      containers:
        - name: outline
          image: docker.getoutline.com/outlinewiki/outline:0.85.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - yarn db:migrate --env=production-ssl-disabled && yarn start
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: outline-config
            - secretRef:
                name: outline-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: docs.mcnees.me
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: docs.mcnees.me
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 2Gi
