apiVersion: v1
kind: Secret
metadata:
    name: outline-secrets
    namespace: apps
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:tvdK6nm5xEGsh8FqbbmEXoARDEGpp3KwMjKjWZqu79LhBndjzhesK6mjLneb2P0XnYryw6ehsjNhGKAexoQxlA==,iv:bH1FuaNQOjBXA+YbZdJkY2A7NTbBY8/H30QXEfyL3sQ=,tag:JzpDHoIBpGm4KFcwjR8lyQ==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:JYJBet6qWoPD9zsbuv5h6w3bbLoZzYolBUXifZyqqbWG7bPYqMGVhAfX+UA+3bxnwjAdOePrw51Q31Wtn886ug==,iv:xaoSb/VZvoInK/6ZbxDPVs/vy+YE+5B+PsuwdrZDzng=,tag:TBhiwlL9/3buFl7nG1hS8g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:LiQm3dYfJD/xv6HVaCsBXUh9tgcGcM3fhA32JlZzGwUCaFXtbcUmWk6ESI0LzS4U6hUr4ZgOB666MwNc9VJ1pPaVrur6/die4yAlieamYv3mUCzHOvZwAFjWWfs3l7xhbxeVxIw=,iv:hgTlvqnFRFBASv4xpw6Ye7QEVmNOktFp68ZYrTfvid8=,tag:cJQEyeHzMmyOKnNmihEMVQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:rSv5oZDtwYVBZ87ElFIcC24GFw==,iv:rVWTiCKI3HNNUFh1stxz1y8eU1UqLlQ9rT3wCXKQsXw=,tag:jhDucmcpoOthrBXxfGH4PA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:84nw14YXeLPX7W9S6bvpeJSit1rOe2w=,iv:3u2UVTgMVboXmIXkLq2WDzhsqDgeTR/igPLirRdK/7o=,tag:QsXRDmddBYmJF5wvtClaAA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qq1QhYqdy3Hl1abYyJXp/O9K9ERUwsMTkVIAl20KcP8=,iv:Uj9m3ekRo3/vZQ3ndd9VvtMaCfTvr6z+jPZ3ciV+oe8=,tag:vXBTcY8I7thE97asoHtQfA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ejBIiNLeOFZnblRLyT1qfUkr3HGGmw7UTQnZwRjderkZx4y5gngfjurKsoezn2qT,iv:z3Mfr2nDei0p1geGLhm03Te0Fq3iwT/mtz6qkjtJt6o=,tag:t7Ot6Gd/n/jx/FN4+0O1PQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QzRWc1VPOTZtRWRFeWtP
            d1IwT3BpZElHeTMvOTY1czZVa1dLYmp5dVRzCjR4Y00wOG0yQktRNWQwR3pOM1U0
            cjRvZDNTK0JmbWZROUlGbEM3aUhqOFEKLS0tIGxJMGF1TXdtQWtkT2srSFdFQzhP
            Z2YzMFFGQ2lsOEtBaTI4WW9MR2t6VWcK/UKZCDsu1qDVrfywCzQpNNaPJeqw9G6L
            KcbXazkAoyKHT9dhOqOMR0jqCxBkqx2GK3uGiaRpCH9By6xXCEWffg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T01:16:51Z"
    mac: ENC[AES256_GCM,data:dCKqyPct+TbQdXhTIJdFhzlRtSdU+1eHUm/0IxwSEPAmr7HgSNgugZGupRoPRut/r76YtbIJ2m0brMXv7eC6qxmxlto1SN8qg/urhMadzflAi4lbuB4zF7IhjW1iM2ZwlELduweTm91xaOrp94kC9GVB6dJh6ivZd5/yhqo7Pgg=,iv:JixaWqiL9nbiZ6P6CbNN55LqwLSedYLL/kjUwvbK6Hg=,tag:lj0OV2l+ZfOMXNiAYlTWTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
