apiVersion: v1
kind: Secret
metadata:
    name: outline-secrets
    namespace: apps
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:at2mL1iAWFB50fZhzPj8+9A8WV4X4hu70Hqb6BBSuRQV/svpwmSvNwUcOJSPUGE7F3jimi0ZjFav3L6aDXt42Q==,iv:GrxCz0lXs+I0QSO03V/yWhemXdU34vIUE2thaZiQIW0=,tag:1zfnl8J0WqSvvWpiqLRmIg==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:IPtpNhXCnqkKje/oVWHNqVzRccDYa9yFbZxF0QKucoE1BQfcrRUnkJC6LJqrgkWOxDLLXjvyexLtv3gZJZ1vZQ==,iv:o2JriAcG1eNR6VdXG17bE/K4nDUTzMkMV/B0vJN/Ppk=,tag:aMAam2zsVpn2m8hnnKkTmg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:NOXB3HNB9OpyFqmZqpTtGN8lkEHbIq3bGBSMNE/0Zx7MK6j38PpN012VkRinT1XaZvA++qbxfUjmcSkeJKMTuWwhRYAQuBHrVI3nvTV0trfN5V+zubgpYWn5qF/M6ZnPJFzuQ8Y=,iv:SxW7dst7U27TA9xtrXzhUnsBZ7mXmWNbo+WANyTnvpc=,tag:XYYuMztkm6XTwBOAB2ZhQg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:icia510RcHUxUAXEPQcrNwj/niXuEWDH5g9jcoVgeNu8CwU0,iv:fFmZPt7kFiFcLadEI+tgbY6NtXvg26I3MqPlZErlXv0=,tag:ja/8KPck/4XB7ertOro8wg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:KAsFdytR0A/rjLlN5YFoe4Qa1suZX+3PPXYU6lIJT04=,iv:+Io2l4KGpHKvoQnqRN3XEKxcixopuVgDVKEMGgdpdEI=,tag:MIxi8PbHTZrFdQ9t/9w3LA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NsD0NFuxC8TiBPKrg8eoQt6yUhZ7ywxP7utQiDErgIg=,iv:YxeYgRvNshUOhNsRP6JAzwd4tvGWdHprvOMjkwHBIUE=,tag:thsYNq7oO2zY5Pn3wg7yRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ewX/Ppo9xgR0Fz4KfttF655MYJeOJePgCuCmftDZ/tycbUxrIDXXoiEnkN//b0K9,iv:sDNbejoaEQ/267aBGgLahLLYyW5zlJXl+JNqEarHTYY=,tag:c8eBDFAX/agMjcdZgYZMyA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QWpiWDN3bmZ5QVovV0lT
            TEx5SHErSFgycTFySGozNEkwVUZVT3V3QnpzClBSYTJ0UUxxNE5VRmVobFZQUlZL
            QkQzRXFiUjBpY0Z5UVkvc2ZWZEhuSTgKLS0tIHl3NHlJT0RYMFIzUEIyYmlRYUt4
            SEpLeStpS3Y1clZqRjB2Wi9pODZvSmcK6XVchh/YkpR98mv7nHOJCup+fb/Eno2X
            wGIupguoF4cpK5d61LYPSFo4pnUWw0LpIfg0PNeCgOINprniH5KIoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T02:10:00Z"
    mac: ENC[AES256_GCM,data:h82km8a/6oBfvuzOnyTE7xX8lcJiAPU8dwxtefcQLxrzjmr/e2/4TuvpL1P/Pk/FOp/PyDb6QYVTkJWjQVNqkVXXl4SnW1yf3qOF5mKeULTPT818iEJ0P1ZM22lzPkM2sipMqXv28hjKQ28ARnViPyMzdghG+UnmmSEXQ2dVk/M=,iv:hycsFvWVkFs9Mg/HWyViCzP6pDjLIxOp/PZXOCHpXv0=,tag:4nkdT8XGiS/5BrPIY78FFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
