apiVersion: v1
kind: Secret
metadata:
    name: outline-secrets
    namespace: apps
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:J0NLBiJYeARMdNgHxBZxnHD+Q38vFYC9FLgmAL8CAwprS90/k7NhetT4TJAW0GxIUvvRuxQUS+vNT+gyzaVNaA==,iv:5W6kFexS5fzBd4tVQNeXmlDl1va+3g/3qvtovP/4uAQ=,tag:cnlBqqYvya7f7YuPYSCeDA==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:PQeM0t0L7L/r4wVbNVJZFGy/vjhBCJVoBYSwKtZnDt6kMcCzxPLgETN95pKV5hB+SuuRlc/IxE34ldBqmqMfQQ==,iv:zeIVga4xoajGAZxzdcR1L/DExeQSMQGExZKQEE4M5UY=,tag:MNCjkqmuiGEgjANWK335ww==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:rRWPWELXp42oVizAbhYfj4sudkULVeicYdPeSXhvmGDN4NUZd0DMz5ttNbzER0xJM1jpISG3RKkWsRt6REND+OJNal8/S8kMdqSVTWPeZjFdyN79Zh+FW8h2pRXMsmoLHsaIr18=,iv:/x2sa11I5HaVikAk6gXB87WdbBTj1rPu0n8JndPNzkM=,tag:e1KGHpCE4d0dIItb1AV6og==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:+Oltny+B3Fz9HJ0aiDzRvOVpnQ==,iv:gVyGPvWp24vr0nXmf2evvK60HS9Zdhulei9Zvm8sQcQ=,tag:xDdqJxJA63n2Y99Pey6irw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5FdAtvTqQUbErDFludR+HbEOx0eWTuQ=,iv:onR4lvbw8Ak5IV0meyER6dAgzHHp/TjN5K+qEmczoqQ=,tag:JQ8lrcjadlYWHIkdwzGUSg==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TDAybXZYR3pSNlhod2Zo
            elJicTdjdUhyWTJvVEttaTlRdnpTRjFHbFRNCnlCaGszaGc4REFXcU9jdVpMdVJQ
            cGRnSlNVdkN0RXhYZVllWXhDcFlwT3MKLS0tIDE3a0NzeGJhbDEvaDB0TU5CNllO
            eUIzSUExUStvb1NGa0ZRdFpWRGhMemMK5q3Pzbw//YJC7nvT7J1tV1pqUl2WwGT9
            WVoQZ+jcl3lUAvnc3MTbY79JsDjINxKxc+g8nFm2zQbeQbKbtnkRZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T01:04:50Z"
    mac: ENC[AES256_GCM,data:W3N4uT7jsZQgbs6bsrkeSm3u1N1mIGhBwzv+aJU3OCsrIDWL7wXWgGcf35qIupgW+sC+uACzFOxWTAvlrgy2g0wRLaXuWpM5t9QmXoAZ+u0lexilkz7SGXY+CcbFbx6/Jysja4Id/LIBq1RkS2K0GYi7EqRT8z9OIP8uhuMW/dw=,iv:Ig3qt25+lfjq2SVAT5St96XeXMOtkhju+UnOQ5auqxI=,tag:O74zbWMGMYVvCj7eLQE4Ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
