apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-b-config
  namespace: apps
  labels:
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard-b
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-b-work
  namespace: apps
  labels:
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard-b
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
