# The same admin credentials are used for both adguard-a and adguard-b.
# After bringing both AdGuards up the first time via web UI, set the same
# admin user/password on each, then update this encrypted secret.
apiVersion: v1
kind: Secret
metadata:
    name: adguardhome-sync-credentials
    namespace: apps
type: Opaque
stringData:
    ORIGIN_USERNAME: ENC[AES256_GCM,data:ROq2xYoJRA==,iv:m1CeU4G+paaRp/WaSK3V4zBeVa7pchTPaNdrytMaBu0=,tag:sSc4bEbn1kinPB8sOBZnEw==,type:str]
    ORIGIN_PASSWORD: ENC[AES256_GCM,data:MTsv6p/ds8c5tZzAXgsbt1hIHmBAbDwp,iv:6R7wS1z+OWuYjiNRYP7XvYgyOgI7h3rd5fMl2xWi09w=,tag:hy/2gpOm8lJjt8Pchz3EpA==,type:str]
    REPLICA1_USERNAME: ENC[AES256_GCM,data:s9j8DoLU4w==,iv:fB9ls91DAhyNFuFYV05yCeKI6dfh/HrZeFfEz6FRHIY=,tag:mHMQoTByW3eBEbBgh9IszA==,type:str]
    REPLICA1_PASSWORD: ENC[AES256_GCM,data:gol36L0soHAShiy/fUgczi1HMmiZ51ZS,iv:Hl7YmKMxYHdBvnvXieODTG9ZPjyXF0bKlcT0NMHsxbI=,tag:tlMIBNumZj/o+S3t0HidGA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbXFuaGtKVWVwLzNjTEo3
            ZGluYUhzSXE2TDhLb05pa0Z6MldWditLL1VBCm1ObXhvZmZyM1I0ZW1mWVVIZVVM
            ejZIZmhMOG1wZjhvRGdwV01UNEVFVnMKLS0tIHhGaDFVT2s2YWhsVHFSVGYybGJ4
            VVdyekpNa0tSbmpTMWttMTFFOEpSdVkK9Oa/1CD+r5PlJD18A6aZPi9WTwfoe7i/
            axLR0SCrSB5GStpRHmK4z3/IXAazMmjAPshzPVs/kvhBAcIgHBsKxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:30:42Z"
    mac: ENC[AES256_GCM,data:yMJzcaZsUm5bNbWAMDFotyWk4n2SVrbQ/an8106fvOrggvTSm1B2rOL6rsPUttqrtrkHTScUs8yCYGCVH+iIi5Ex8xa5zAQrxm6qNebs5ZvdCSVUKE0Xi4VpZS1NE4V0p+DBeLa25Ax03Z8TJjBp4t2u/0Az7wZQfOKZEB4ckjs=,iv:ku2+RXEddm0OKW+EmgZcwnGfpus+dpy+FlPD2ptQAtg=,tag:AUCwY4fimjzyE6XZpgVpoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
