apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - adguard-b-pvc.yaml
  - adguard-a-deployment.yaml
  - adguard-a-service.yaml
  - adguard-b-deployment.yaml
  - adguard-b-service.yaml
  - adguardhome-sync-secret.sops.yaml
  - adguardhome-sync.yaml
  - ingress.yaml
