apiVersion: v1
kind: Secret
metadata:
    name: tailscale-exporter-credentials
    namespace: observability
type: Opaque
stringData:
    TAILSCALE_CLIENT_ID: ENC[AES256_GCM,data:/hgU1/+KMy+UKV1wUNF9FKw=,iv:hA+Q7KW43zWOwcrRfYB6SxIvAeW6r67Jf7Zuv6xCuHI=,tag:xsLT4hvVht2Ac6T2AQOhpw==,type:str]
    TAILSCALE_CLIENT_SECRET: ENC[AES256_GCM,data:D7r/UY7JvCrBQGoam0Uty5ymKeaRh4BM0n1yrSfsxieJpKb2IDtT+TX1erk5Qhe9jGrmA+8JEpikrr79uKx9,iv:aElWwszVQ7KpxPJuH8273xdxO1SRHXaHiffLdnv5H1o=,tag:n7yzOpG/IWy3s3mRZ9xefQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTHhzRXJBNkE0Z2NhUVNQ
            SFJWYkZjTmtTTi9sMHl0MTcxUUhCWU1SL0c4Cm9JckpjcWIxZnBnZUl0bENJdnpP
            RWZLcWRtMTI1ajYwVVZUM2cwR3RBWXMKLS0tIFNZcG8vNEF3M2RQNXYyNURkcUVu
            SEY5cjFjTTZMOGJ4YzV1TWZ4MzdPNjgKLD3mTT5TmBpxRp9tc1hktkxmqgrU/n4r
            nGJ/7wMUiwLNr8Wfz7NhMNMbbd9+BdAKrx11sEELY46x4+r2tUjG8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:48:43Z"
    mac: ENC[AES256_GCM,data:YoMuUwm3ERdoZcQPpkL3+pYdwDCDLW6XJLRfuSubDc/pxYlkLGDhBvVZffLKhsJuIHCcB7DtLpwsuwAhsW6c1YKWNTHokIKjnWgfEG1IuydS9tffaU7Jl0AFv82x/83HyyGPcc0FDDqcIDXxUOPuqQKR2bRooW4VuSehDUGSaR4=,iv:pwbW9Wjy/UZKsKFV2eWxMq+JUzWt9Jxr6qmCi+ECSE4=,tag:9lQeJ4/omMrI1m1mz43ugQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
