apiVersion: v1
kind: Secret
metadata:
    name: lidarr-kids-secrets
    namespace: media
type: Opaque
stringData:
    LIDARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:9KGUHS0+eVo44eYPEv6bdm//loe8fDnTo8ZNSdM54K8=,iv:6GGC4c73XgaHTusn0nwdA8+UzqTIz3suv8mOrEbLKr8=,tag:wKubcnvYyWKNEsEPdWSNKQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY2luU2o4OE1pMU1JTlVD
            cW9qaG5HUGRzZmFvTVlhZDRkYndqRnhmaHcwCndUZWJkcTM2Um82Tm52dTNjZUYr
            SUQzTENtaFdVbkkvZVpNQ3lVbTJEUVkKLS0tIE5EcjZVdmlyWTVxWWI4UVJDbUVp
            V0liUmZFSFVMOUhWekJKdFhTS3R4bUUKmoE0GWeJ7mdzEbU9z6YbVgzr6XxcV05x
            V1Qes2x8p041C/CNb8AovagsMdG3+YIwgsJ3y8YztwaPq9psTsyXiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T22:49:31Z"
    mac: ENC[AES256_GCM,data:Kt3iC0oDhsn/B2lQJLIM9e22TgXWX253+LiRj3yLLoleucDn1aS4wUIYiFQF8/jBr6VX4IEF2Q+oygU2KkN7wsUMby6ZTUv2irAmHf1jXyq2U4lo/kWpUeUrcHVRdyT2rqV4UVTwDz5b66cWXa6QUAjP3M4MgRu8Df3YnG/3+zY=,iv:qjiI/pdO0wEPt9XImggVDbJB2yjbVghJ1x/sn+aVKGc=,tag:HDT++d5c2bfdGusMZX4kww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
