apiVersion: v1
kind: Secret
metadata:
    name: pelican-panel-secrets
    namespace: apps
stringData:
    APP_KEY: ENC[AES256_GCM,data:iTsNCKhocQ5XmSDq6T1Fl4xR5S7xcsikx+eqtYuGkgowwbPGdQjc2H/qzfDDKQsCTDeC,iv:m5l19ISWSFWzpzSTYDaJj4lGLi7z3XaVITiHrGYeapk=,tag:KLyC+IGftsLx2KEMEThTAw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:mKQSg84zHuu1AznFH94dTMxvcUNv7cIDDCTcYU348vE=,iv:OLeNBBoENdran8YFEK5Wxw81cuDzZJyYqw/h1uxlgXg=,tag:8KcgyLw1tnlHCH4SH+/9uA==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:sSfC26sP,iv:Tt/ssf32oDoNI1lJTPl/y3wkOB6D4BM5EgYCdOigRi4=,tag:kdWAohUfYKOMuOnDhBIOMg==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:Ifk7N95rKyPWxCsNCHBstWp0M8R8+SF3MC3VNlRSOWH1pGdL,iv:O69UuPFplipI3Z1KKcpT+Gb9q/KX7sQ0y3wEPK9fLGI=,tag:4KKyv0cVHATte6Q+6Qd08A==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bHZkNzhUczRQSTgvYVhi
            MFVURCtsZGxMNkxQZXh5VHN2V0pjTkNrcFY0ClpmTEMrUDQwdHFycXM4WVAxbE1j
            UjdqVU9XYUJ4UzFoVGRoSlh5MGZwcTAKLS0tIG02Zk9rVHJEZmo4UWc5V1JCOWR6
            SndxcnNaL3h6YU9DbTRBSXUyRW5vOWsK7g5tgXw1IiC+iHVxVbq4aM27AfuTlKJi
            nNC4RLwy9BpOI8gBNlmvIb0hgqFjgzkSPIaM62CjTqXYLTxDaVwTXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T02:45:16Z"
    mac: ENC[AES256_GCM,data:0iIyKzeck1L+tcFJRXPnaHaQ2C62ncsU+UhhHoKMDBYBz0U5tvGcB799Tgv2j1EOt/vzh9UTL07AhKFrxevjUVGMfTFSYAucDMSBk0azfFQHXNvH9t6vFw1GK5UgkwehEOEPP9of6wAqxIj00aNB78wnYgSc9iZfO4aZzrmU5B0=,iv:rnC86/4vvKZXutCgvKkc3naFJWaUUzlD/rL1Nec9ahk=,tag:ID26KO0ghm9j6zhNPWZ/Pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
