apiVersion: v1
kind: Service
metadata:
  name: pelican-panel
  namespace: apps
spec:
  selector:
    app.kubernetes.io/name: pelican-panel
  ports:
    - name: http
      port: 80
      targetPort: http
