---
- name: restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: restarted

- name: restart signage-kiosk
  ansible.builtin.systemd:
    name: signage-kiosk.service
    state: restarted
    enabled: true
    daemon_reload: true
  when: signage_enable_service | bool
