apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-gpt-prompts-ceph
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
