apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-gpt-prompts
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
