apiVersion: v1
kind: Secret
metadata:
    name: paperless-gpt-secrets
    namespace: apps
type: Opaque
stringData:
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:WzufzyhP0OWH1+YVmENyUGNmLaLru0Us+rfZ/G2sTQpKQXSbS96Klg==,iv:3KP9cgg8Ff5nTb9u2tZnhJCiAMAlYlPQdsC57YoHdis=,tag:5uVs+41YlgpeWg5Qvvq1XQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTalJpbFlqbEI1aDJuQncw
            azI0QS9LU01ENjhhZHN2L0RMUkEwZWNOU0I0Ckh6MHVBYWZKTXBvY0g0Nnh4ZFBo
            RExMZ3dMd2RSRE04OTJKN1lBMUhLV2MKLS0tIDk3VUJGTXFwSDdudkFuTGZISkwy
            UGpURTVVemw1VnJrZHpjSlY0NW9jcUkKOd1INnvtLAxqR3GRlBERjbyD2vO8Bg2b
            5Fj69TG3ayDIlRbotS5QRwGtQFIh7VEORcv+KNp44ZUyWruHiFNraQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T03:32:46Z"
    mac: ENC[AES256_GCM,data:0SuuwGtKyZvEnaqlTGGSvbbwrVJqBi7byV54XN2tUlhjdCs7GW1+prDOwREIxp5d19pupjtIsUJCeyvn/gdga6+zyQ755ptbWZAawCewEm6x4jBHhZWwghwyjxgxCBSZz4ol90QVjbbxBA+vcvAxNA3UojpC/tZEWPQB8XO7NtQ=,iv:j9FCfISP+zKEBcVdtf579kvraqu8BYxGv/j3h0yMkq0=,tag:+GgTdzWECRIBHfBUmSon6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
