apiVersion: v1
kind: Secret
metadata:
    name: paperless-gpt-secrets
    namespace: apps
type: Opaque
stringData:
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:rTp64JiACtvhH3e1NfQMTuZwfIjPQTE62JftXeF3KSfkYrR4UM0yPg==,iv:JPJCPwFRfucdqZoHLP+CI0/8hb3AjRiw8Thr80bnA4M=,tag:X85bKz69ZEVIqwsdZa273Q==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTalJpbFlqbEI1aDJuQncw
            azI0QS9LU01ENjhhZHN2L0RMUkEwZWNOU0I0Ckh6MHVBYWZKTXBvY0g0Nnh4ZFBo
            RExMZ3dMd2RSRE04OTJKN1lBMUhLV2MKLS0tIDk3VUJGTXFwSDdudkFuTGZISkwy
            UGpURTVVemw1VnJrZHpjSlY0NW9jcUkKOd1INnvtLAxqR3GRlBERjbyD2vO8Bg2b
            5Fj69TG3ayDIlRbotS5QRwGtQFIh7VEORcv+KNp44ZUyWruHiFNraQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T04:00:49Z"
    mac: ENC[AES256_GCM,data:97IvB8dh0vkp4Vw9epXAYsE1+5vGL5bw0OV08kAuiwRboZ9IBNvz8VsGGt8ukLNLt9Fy13iYQrkBr0NrhIZx7Yzlclo1/gO4ErMIA8ygakdjCej9dUqsEdIXFJ+2TbPw+sIOCWYcfwgw4H8P5PgKqXsM7fREtmENbinvB8gedkc=,iv:QAtJ7YT6Nd969EhO3BEmH4b3JP+DHil+vKk6GQ+AE2g=,tag:YTL905Z0pE9zcOEcUfLJIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
