apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
    namespace: media
type: Opaque
stringData:
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:JTy6cDtdwpDKVjrzwLDlftzo20ZBsnJtgksZ4GnOO90=,iv:MhPbWqbsPLrLLL3OLwBq4SbqpqIzb67X5xColu2KdJY=,tag:P/W4b09B16yfUUG/yQes3Q==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NndiQjJUSHdwei9LclNq
            WW5kSFlySE9qTEgwaG9KUm0xWGxWMXI3dnkwCjRqY2NBNlhIc3g2SU8vd1pyM0hm
            M3gwSVRnS1V6b0NWdFhlME05ZHY1VkkKLS0tIHpTZERQTCtlOWdtMlIyR1FmbC9C
            ZVUrT3N5aHZHYk5LMVFqWGh2TWlrWlEKCap1OR6Qkyarvf0kIpFVdJrbdGB5yUOd
            h5hY3RRjM2J+kmpgBx5JHdkF8w/P4dA9E23KlzEBrwnQnVPderhDSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T16:44:52Z"
    mac: ENC[AES256_GCM,data:kJPddxcHihJQjV7uLc51jIAdohSYp2aGr3+MvOZeLBlKH4UyDimyYO9tHiTZHgaA++ToF8mmc++1C/NM4pYD9Zxai5+rbvonGu3sPrTXVu9W/ufNGDxt9Cju0ZyKn97HIO+vokotjN1WhL0txiRfCEHCciePSGJz94xSS/4QRcM=,iv:304qaVlGas83/FaMxB33xcn2ALsafocJLmzERBeBLEg=,tag:vIOzj26VkvYhVPBKCL0yrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
