apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - sonarr.yaml
  - sonarr-anime.yaml
  - radarr.yaml
  - lidarr.yaml
  - lidarr-kids.yaml
  - bazarr.yaml
  - prowlarr.yaml
