apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:seWSyPIrAnE6UrhCZHCDmtxQfMvTtUMzjUv1xEv/TOM4+FsWa5r44PbOFHF9d0jynY14UOktSGhdFOcOpy2nrK4/h1uqtys3,iv:fpX77yeUhtC8Y2qSdcyp3OQTwZuKWLZQ5uxKsk3N0eo=,tag:Z287pwATY3wIkBB9faUUhw==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: infrastructure
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbkR0S0dXWlhYclE0TXhx
            RmRwSWhld04vZzQrRTJVYkpXYVZuRHRuZ2t3Clo3QUNFc3AvSWxYcDAxNzZ4RFlI
            b292YUV2cmhLOGwrVWIrM2x5S1dtOTgKLS0tIEJ0czdyRTVpQ2xxYjR2RFZ2QWtj
            L2RCZTc4czZEU3RMVnFjYXRuUGtaMkkKySF3Y4SU3W1tLiF+gj0G2MfW5/tRKDiB
            1oawEeYbxOvaVgyeshYJeFZepUS1afvGP9HuT+HyWjq0c6eZoYk+Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-10T18:36:56Z"
    mac: ENC[AES256_GCM,data:S4xnq4tq9lZN5CjD89w8+Cc5T8ioMumIkAkEItSycYlzPBDdGs341/gsLTTr+gNFNQxLrEJJ0aVdNICe78GDh8l1/sMMJ8reb9EliyYHeZjN6+cnR/5SzN5Csq35QCL5prfL3gdCe485avoRVMPIf7EDLOdccChk7IhES3+2UTM=,iv:h5ZDSZ+QYXXOlTr1bnb5eCW+rpJlMqIJZljMQwqd5jk=,tag:UPPmV9PzlzXbH1X4YmTOQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
