apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:PgsJHIdFCbgQ9BA9suwuYuVsOlf2CHIUdlx63BVITGCBZKHl8kpulhHQlfpkoKYWDUpkVLyZdT9HRIctNe7QA6zcd0MNydm4,iv:EzxWQwepBdZde3qCM8B3uDQ5FFBh3dWRaN0sxeoIMcM=,tag:1Lih5Nii7CG8pbhAwO39kA==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: infrastructure
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbkR0S0dXWlhYclE0TXhx
            RmRwSWhld04vZzQrRTJVYkpXYVZuRHRuZ2t3Clo3QUNFc3AvSWxYcDAxNzZ4RFlI
            b292YUV2cmhLOGwrVWIrM2x5S1dtOTgKLS0tIEJ0czdyRTVpQ2xxYjR2RFZ2QWtj
            L2RCZTc4czZEU3RMVnFjYXRuUGtaMkkKySF3Y4SU3W1tLiF+gj0G2MfW5/tRKDiB
            1oawEeYbxOvaVgyeshYJeFZepUS1afvGP9HuT+HyWjq0c6eZoYk+Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T17:39:36Z"
    mac: ENC[AES256_GCM,data:c62r8qWwtjs93POndnSa1wIiMoLdqkqvwS79lvBNrdoZ1awrjStP/7MN1e0VMGH7chmDqt5nVjBVlJE3aKsPHmIxTx4sqcLDL3/0Z9Zp7dYj+miP4csdIfqyxpxeXdHBXsZQ/Xt8ceMulYJMKiT+AecRCF/HqnLATHdb+GI16rc=,iv:js/yRxDyrD8GFxVj5kxeQei6NcxakPgsmDskXFmokII=,tag:pdpoxczOQbjJqVkSvg9hwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
