apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coredns.yaml
  - cluster-issuers.yaml
  - metallb-config.yaml
  - priority-classes.yaml
  - public-ingress-middlewares.yaml
