apiVersion: v1
kind: PersistentVolume
metadata:
  name: mempalace-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - noatime
  claimRef:
    namespace: apps
    name: mempalace-data
  nfs:
    server: 10.0.1.1
    path: /mnt/data/k8s/apps/mempalace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mempalace-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: mempalace-data
  resources:
    requests:
      storage: 20Gi
