apiVersion: v1
kind: Secret
metadata:
    name: version-checker-registry-auth
    namespace: observability
type: Opaque
stringData:
    docker.token: ENC[AES256_GCM,data:SGx5mQSrgF4vlYwXdgz/AP6HXm985IDbeD7EHzXSh/DOQs1V,iv:+oL7RaPrp0ZTfl/IaYynwgMI8ohs0k0DeOnL8vCFbsc=,tag:LQEEQFvYJs5zjhGFlx8w5w==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTjQvcU4vTXprL2Vyb3Nx
            eWNCNDlNOU9iRW9FNEVkQ0xoUFpZeUpJVDBBClBxVDdSdmVZOGZUZVBLVHVsbWxi
            WDVwbXduYklhRFM1R3lVbDBTRmF3TEUKLS0tIC9JdVFZd3EvRUprZVltQ3Q1YkVH
            eTEzWG1yZWpCNUdQYmIzbTBSTDRTblEKOwY8YGDFqIigp4dkJ2BTComWt/lAKr0L
            YeixJXZBCpVQ05Px0gpnaQokf/gKeRkD2Zd3wMwhYWLUEmCtoSkvqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T05:10:23Z"
    mac: ENC[AES256_GCM,data:DxbJfx4gMAWnCPiH0NUcxfeBLylsKy21DcMkkRP2Y/iGAeO+qfkRlIqDdvNmqF483p146JHsi2RKRad/hlinorbg8ZfsLnEBHJsJYC4e6ogOyI9tvaIjYn66O8ogGiYa7is2fyHdPigOPuU8iHi9eEnaQcv2cVDzp17lXa+ayk4=,iv:FD4Dxn+0jqMdr10oCxZ7vRkcOSdxmGoKfTYrgYl0P6o=,tag:J3zPi+d3zl/edSDKMw0ANA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
