apiVersion: v1
kind: Secret
metadata:
    name: version-checker-registry-auth
    namespace: observability
type: Opaque
stringData:
    VERSION_CHECKER_DOCKER_USERNAME: ENC[AES256_GCM,data:dyyRVUCVaATVlfFaSA==,iv:67lQhpaerehcrLOPGWklaJQNDwu9/jm2Rq3YvWFDqcI=,tag:Nf/EjK8ije4DDQeRGHvASw==,type:str]
    VERSION_CHECKER_DOCKER_PASSWORD: ENC[AES256_GCM,data:Qip0pEK2gsOJ09DIvlgfpfZ6mQCCraKa19RgbW7TLcuNPCds,iv:z7kngGak2x7I/JjIdfSGjdy2AzL0f1kNcs4PYak3Oyk=,tag:LH+2cNMRcuZw0OUb8FLceQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZHBCTUZBeEVFc2hPS1dW
            bDNta1BERHlOdUxzT2h2ZFM1SDRUelZEQWlzCm9ZUThpSDB2blZ4WEdYSlVGQ0Zj
            L014aUtXTkJjdnc1ZFpKM0RCWU1uREUKLS0tIHg5NzFZTVdlVWw5dkFKTWN2MEQ0
            VWJMRWhubE1JVUhsbklRYUtNUHEzaTgKbGSxHjveEWRNS6+sHjYlukAYRpFVDhjT
            +1ScS7sNIQ0uY2+pLoKROUu6leTzxDPNcZoMV3rbRI7CLAMEbnWJRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T05:15:55Z"
    mac: ENC[AES256_GCM,data:SwyXLMG88c68gIjmPCDOfz7w47KPzETlF+5IwFJ6954eBiD44/EsZciCcR75VJTzkfI9yp1HDDnGYxCJ3a3r0c6Ms6xyenyWhtZLW0sW6DbZyD8XCjZSnRzaUlaBNYIC2tLi2mrg//qYzjnWeXUtyQtojHCkPO0tblwEYRltrOA=,iv:WyPKb1UWPrTbgmMnwqKMu6mNqIp88v67nacGmWOLTno=,tag:6MoqfM/0sFOff0UpMistiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
