apiVersion: v1
kind: Secret
metadata:
    name: radarr-secrets
    namespace: media
type: Opaque
stringData:
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:l6Dvp09yPosubgwc4/T8S0GDEPUKWEF2vk0UO2uro34=,iv:0k9EFmAsxfymQa8j74zvVhEZfE7Eqt0/ojAnDjchmtI=,tag:MMtfRf7GnMnuJPRkPhUw2g==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnclFSWjlhRzAvMDBudXBR
            RThVVklMZ2JnQkdjcEhMOHRTUW9XMm4rZURBClhXWStjZHd5d3F2QjhaVE4rWDly
            NCtyTE9Ob3dIMkw0L3ZZUXJqdzRERWsKLS0tIDBWMERYc2ZkNzZZMk9NeXkvd3pD
            ZVFsa0x5elE5YVhrZ0dzUFZrczFaZHMK5LrVwGHryOr45GuAB/V+d4BINczRVi8l
            ja1DAizrvnhrCnwFqWIg+csPpllhhVwqhVqonBL0QouLRZdDvlBajQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T16:44:59Z"
    mac: ENC[AES256_GCM,data:iLlMFhzvSI+JG7e4UBDLIQGufcbfV/ge+juPQZUPTXkOoPcYvKucdcVhrLXI9qNYalZ9jktUKj/ryhkLUVDbziwPsinUtRN1aI2tkgg/08XA7vrePkdyTydKJm3sNnwwcbQFrqXB5NKcgD99RBzITEo1aLSE8zTUATWbVlHpz3A=,iv:AgWxi4JPSXF2z/BJ8BFHkVs07NzuGSKc63s86Bf2zZQ=,tag:BW9+CaZRxvU3Ysf3xK6DpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
