apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: questboard-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
