apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
    namespace: observability
stringData:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:Q16St2KEQSFSYKE=,iv:COAwKOrbsNN5LLt4W4jnlWWiLwjaIk+fW6kaIa88VIY=,tag:D0maOpluR83ojSbEKFjqVQ==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:yoNp2gM5++PeJGz8RSv9f8aCdIhPyO5kZFqqw/5R60IdaSgrJUi9gwf5/k0=,iv:oYCfhZgDFCaI9yJT+dsupcHnf1FGDfmnatOzRASE3L4=,tag:c8CW/+prCnQkS2jzYMTKHA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERW44WCtZekREZ1Vxbm9J
            ZkRaYzZtU0NaajlFS2dpdWI4SEh5VXZmTFJVCkhJR1RTajcyLytFbmVIMkJQa2dZ
            TzJQVjNVYnZiblRDZkFINnZpVURyZzAKLS0tIEFmaE9Sd3BTZUUzb2ZXU3FXWnNE
            VWJEb21jQmtGSVZaV3FGLzN3M1pJc0EKf2reXQyQcqvX+/kNuD5wvJVRYp0/62oB
            hJMyM29li5xkBo61jEqBpaQt35oA12Qgc4mqKUzBG9kp+qHYLeJWmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T21:14:32Z"
    mac: ENC[AES256_GCM,data:aDeeJj3dmHbScF0Meqb8mKyKXbmG9FnwcGluHz8RiUmJBuvxpLjkwUWagKStDOchdC9tkYWfiNkW865M0Q0ZnCnKZ/UZU4Hy7AoU5hVdX14BIDqn3NF9UiYXPUDc0xPyvaQ34Z6Q/xnBSHde58mbZ039Z+GSsjpQITfqmGEly70=,iv:1E1qtHjvlLG7O2xTgNgOuMKUvUTpjPFQL1gBuyR3B08=,tag:iWoNarjp3UErQZdzTY0vQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
