apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./temporary
  - plex.yaml
  - tdarr.yaml
  - sabnzbd.yaml
  - pelican-wings.yaml
  - truenas.yaml
  - proxmox-transport.yaml
  - proxmox-latios.yaml
  - proxmox-latias.yaml
  - proxmox-rayquaza.yaml
