apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: apps
type: Opaque
stringData:
    secrets.yml: ENC[AES256_GCM,data:yrI81jqH75eC2o1NUzL6OI8E1EHE89ALcN3RgOEbnUUJIj7H995yrGD9pJAyvhIOqEbL9ABrh+ufgQJRMmKTEWI2olhVmLAqzFAg4TUGSS7QyClhF4Fyi5kpKQUJeT8M8DJpkTB0FM1Ubn/krIWyCPc9bivAPBlErW3KdMoAOGUgbw9Ia1xhOsXzYXoErhrAqnhbn7Z/TILSNB5vOcL9igUndcxL7gFUx7ywrbobVgh8ECuNv/agVUU4xcgwkG8ORcpAU1z8lTGbmqho4vC53cJZRtc20QrioV+m4sgyzu4=,iv:+3NVIEbFx6FTs99WmHYUaiMksSmBh1klELabH468RG8=,tag:z+DsuvNARaUqn0VRgFHDhw==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUXNJYThEbDVvYzIxcUR6
            S1YwRXN5ZVNGenhJMDd4TEhGejVDVzdtVVd3CnNUTjNqendYejdBa2VQQ2NuMUZr
            eFVDdklNTmRaSHQ3TC9HNUpkTkZ0dVUKLS0tICt5dHZiM0hBRXhpcUdpVkJyc0Vo
            QnE2UHducmpBVW5scHJtRDV5Mk5KblEKKWsaXJ4ZVCpoE4NZiF6xMheizuKHwxhG
            KhRKOeGTh3wC7zcRRFRH1009IIAmFPAriVTyfL58SnTrp5wB/qQNkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T15:16:16Z"
    mac: ENC[AES256_GCM,data:xVu5/S42oE4xvxEugpZ/UYT/Kjh82yQesQX12dnxA2HG3WREIgGNTiebDyibzo7/imIfX7zzRTn2DMZrKIYJab38kp0gtORIV/kMXAb5SaqyicPDktjn6pb+q/1xB4OPGufxKiKjCVAkOkRriVT1/UqTShGNUnL24/W0PrvLMI8=,iv:f76eX+lfzuI6J0szMXB2bd+3JcwSkV+9QvdmOV8qRgk=,tag:Pi2zqbg9WlYLWLxAhW7F3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
