apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: apps
type: Opaque
stringData:
    secrets.yml: ENC[AES256_GCM,data:vdJFac1WP/oc27TLco4nARFanmRxWhIWhjR25WLV1YxHhon/8WWUTGxzyKn2Z5FIsM6H/FIzKoEHVBZDSqmIlaTSqtQRu8ZwUpumtnnFFg7+1BXTIZAJveqUmXjVFUMrnk++TnQA4POMXcwd7cL9+iK/2wIEzfTZK5w4KE38mEf3j+bDUk+VYvYo4PIxfDEJe156BfrPctdvdW4GXtyidF0U0HOPpTuQ0BwC/VYLWhGtg3xClihyeFxOqRss8N1NV5mXeGVerGGgBNjFOPo50g==,iv:LI+HIYLwb2JejL0yCUdDOo3b6PE+xhKOGh5XAvKMpJg=,tag:CYgiv5LGBYF4M3qYIQFBxw==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUXNJYThEbDVvYzIxcUR6
            S1YwRXN5ZVNGenhJMDd4TEhGejVDVzdtVVd3CnNUTjNqendYejdBa2VQQ2NuMUZr
            eFVDdklNTmRaSHQ3TC9HNUpkTkZ0dVUKLS0tICt5dHZiM0hBRXhpcUdpVkJyc0Vo
            QnE2UHducmpBVW5scHJtRDV5Mk5KblEKKWsaXJ4ZVCpoE4NZiF6xMheizuKHwxhG
            KhRKOeGTh3wC7zcRRFRH1009IIAmFPAriVTyfL58SnTrp5wB/qQNkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T15:07:01Z"
    mac: ENC[AES256_GCM,data:iB1JYBUn6KvYjiUZYDcd+Kb1VQh4aYTy9e3IH1ZnQd9MSj1nqCjHij1HpJzsPL++4nSVDIqjts1forhEah5HqNU3WDec3AURALoNt+voW3zyC0sAji+nPKV9kUF3FN+P9J6HoyttOpedu0bLo5JT7rW5IEP/jj9tfWO+cosIfMQ=,iv:4GI9O+IJWql9h3dUPW3TVmIqD7tVsMSQsNXm7f2HvRw=,tag:AssVMBjbH2TENJSu9u01uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
