apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./adguard
  - ./external-services
  - ./grimmory
  - ./hermes
  - ./homepage
  - ./mantle
  - ./ollama
  - ./open-webui
  - ./outline
  - ./pelican-panel
  - ./paperless-gpt
  - ./paperless-ngx
  - ./recyclarr
  - ./uptime-kuma
  - ./webtrees
