apiVersion: v1
data:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:EyQ8LyNVSTM+d7vK1IaxWbNijPUNzm7j9hUCbb6Kv8astkal98dZy3CWbwedqRX1Lx/c+3ZcCpQ632tO6u+jWbpOqbLXcXDBHYWpdE7EmexZOc/cdiV8JA==,iv:UIE1rq3El2AhylW1+KfiPZU//hYmDCso5cJ3a3mMils=,tag:weDqKzuROw7rkzBugIVxZA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:oV+sCC0LD8Rd0Z0xggUpnEH4ikV4UNx64XiHOqqK0tHvWHORciKgZYEf1cveIDWgPoJgybfQIFTHwYbpggEum7KHAfoRpeqSM86hS+7juxs7uN7c+ZE9AAyTS0NQRjFV+2UGBL0ID5A3FyfWMdSbaWYj1D7a+0x1mqhK7g8Yb1A6IrjVgahtjoACZpzaDH1Afzi7BYXPn0ptRP7Eun+xMA==,iv:FyQcSKUZGvfkhlZhMjhvqvqNp60ZEoZxmfShWG0j7RU=,tag:1SZh1WWBCMw3pRpYEArI0Q==,type:str]
kind: Secret
metadata:
    name: open-webui-secret
    namespace: apps
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVXArbGVMZE5EWUdGNGRE
            TE4vRlFDcmNMSzVkcUZDRzVWTkhkbHoxWGs4CkkxZlFKZjM4SWdadDA1cEJQM0VS
            YTFWS2VqdUR1elVGVVJ0MUVpRVJKb2cKLS0tIE1Hb1BlRFU2SmVKS3pNak42SXcy
            UVFySjU3MlVoclloZUd6Sk9vWnUraTAK+4h188kIW5EMmhoa5VS9CSvkS6lx12o7
            GxAm03it9FHkObOMalIr6zGloy2y9caiUfR7WBRPV6MfmvY4pul/jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T02:17:50Z"
    mac: ENC[AES256_GCM,data:iIYJaZBUfD99cSVC7XCMWeoreNYELSJdYkUtodyiBqxtjl6zZZatnvYYYx7bhBQ4zr9Ze7QTVHtYPncHiXUiB+ZTiYydO4In3lmOEoo3EyVC2ih8qSysO8izEJa3peRYPY+CmxHvvc4ibS0pdkQzRhBm4CHyRaALt6aJAYvrFvo=,iv:jU/vQJs98/Qb4c9Kdp9vXJQ2Ql1ZzcxO1X8BvZMz2Zs=,tag:Tq1qTpV//MWrVuxzT0IxDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
