apiVersion: v1
data:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:EyQ8LyNVSTM+d7vK1IaxWbNijPUNzm7j9hUCbb6Kv8astkal98dZy3CWbwedqRX1Lx/c+3ZcCpQ632tO6u+jWbpOqbLXcXDBHYWpdE7EmexZOc/cdiV8JA==,iv:UIE1rq3El2AhylW1+KfiPZU//hYmDCso5cJ3a3mMils=,tag:weDqKzuROw7rkzBugIVxZA==,type:str]
kind: Secret
metadata:
    name: open-webui-secret
    namespace: apps
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVXArbGVMZE5EWUdGNGRE
            TE4vRlFDcmNMSzVkcUZDRzVWTkhkbHoxWGs4CkkxZlFKZjM4SWdadDA1cEJQM0VS
            YTFWS2VqdUR1elVGVVJ0MUVpRVJKb2cKLS0tIE1Hb1BlRFU2SmVKS3pNak42SXcy
            UVFySjU3MlVoclloZUd6Sk9vWnUraTAK+4h188kIW5EMmhoa5VS9CSvkS6lx12o7
            GxAm03it9FHkObOMalIr6zGloy2y9caiUfR7WBRPV6MfmvY4pul/jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T04:05:11Z"
    mac: ENC[AES256_GCM,data:yV82w3pUfxKagDEHubq9px28B4PFbFTA1OjuYrrICkN1Yb8Ra7XpNy+QBT1H9a3ucuVL6jqdPGENu2JJ+OQRHx8QeZy5VfrOlWKU19iS2/GLbAjK1E1LLzienti7LHTCEtVZVsSDbmQvhjE3xwwqEqo7fNOLPewYvULSYpfRVS8=,iv:mmA9Zqmm9ESqW8kDpJnAM3CM3IrFtaF9Ry+6EnZeT2Q=,tag:EBgYd/J3OQTH/FYb/I/7SQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
