apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: auth
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:YzFs71NQpiJQA8t3waHJT1oBLlUkqpxU6CI9uN0MH2o9cNYoWUbGLCC6Bz1HjjEjQDL5gyT+fP8t3xjbON6thw==,iv:cSw6i3JP5uxlllsuMR6Ekh7LpUD5dUTUeYZBBgknWr8=,tag:84h6VoJjYyEf8swuHbWj+g==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:AMuY1rDaphLydVJ6/OVd4s2q62v/c7+l8oPwu3gpc7xklepfosyk6DE1uqcBFveXkvNG16qM5GB0cFBj6MSrqw==,iv:wMLuRpguNqdyDDLgJFPfSYPyv5FEqoi6UC1scCZjLc8=,tag:ygJXLiuE5aLrgBzvoGqGfg==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:1nHh/75FjjyjYqZfNGoGIQkLVoUjc9Hh44vws4kqXkxEZrDP5xsGB+ch8g==,iv:V9Yx2pf222UFTCbQwVFA4axnB1OhqcDBu+Rhi8I99Z8=,tag:VPnUvAemdF/Uvtl+uMzTgg==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:W+0gYVdrDZaDEiu42BLGQDiEiQSw4308vr/5hfJQYumweF0pn1ylFnHag9oSxwsVCrjCWIcKzd1K8t4qem/M/mEVtSzTCRU=,iv:n56hXBzIdFRHBNdbbqrQeczu/JdJYHIHrKdDDVXfSOo=,tag:Mm3APkXN/c4rkzoBpC+qsQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaFk4NXpCMFYzQVpTZ3ho
            ejZtL0RXbWxDVWNzckRLVktaV09qeWhVeUhFCmJkU3V1SnJoRS9TSzJ3dExySWVy
            eDdxcmRkZmNUMkFIRXplaS90TzRvSU0KLS0tIExpdFNPVnZUZTUrS0pWZ0R4QnY0
            ZWRnSFVvSElrWllDUU1pa0lOc3JuSFEK+Vx7JHx9zs6wI2OCz4ASFQ1JXh44Sfdw
            yXrwzXzPhK5kG19hOcQJo3dp7NsHlQRkU4NBZ4sqfqPISyHKIGxZQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T18:29:14Z"
    mac: ENC[AES256_GCM,data:7pcoXBmZFiq914Cdc5UbkNjjESoM/HD3hL26sjA4CizBu2ZUeqT6gN8LBu8CeN8CLOlhXK9Zy+fvdeMIy6lxYftcYgurmIWC1sA8Q5nzUyIX9WrHFx3fO++A/M28Gj2nzFpP/4IpWs/CtGW3MBdIeKdLnDlytJ6VeDOtZpjTgQI=,iv:RHZSGKRpLxRQONZpd6ZFgMGgmbwuVh9fQs4vzYPrBvQ=,tag:KDh73RyiUZxVYejYpLs7fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
