apiVersion: v1
kind: Secret
metadata:
    name: proxmox-exporter-config
    namespace: observability
type: Opaque
stringData:
    pve.yml: ENC[AES256_GCM,data:ua2vThry/5avt17HO9O6HqShTYnzBh0BTXG/02cYZ3Lgn4L3CbrKgFTctfGbB9wHQp4rgDfJjMX+qZjrRh2nF2fdNVbbUKUQuS4YLRgu5hSff5uRI0OMz9TsH/LPTa6S4YJK4+x+3xVa/N08WuFj0DRx0tRXp9G0luP4XBk057o=,iv:Gct7c3J4nqc+aQaED3v7GKI0MYIC0DDNCJ1P7QN/jfM=,tag:SyaNwL95kt5xq6o03jxNWQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSTExYUllWFZpWUNwMlU4
            a3FvVW44Ym5ZM0lWRlZDVUVaekZ5ajdicEhrClUwaFVKQkJoUFRybzl0NU1LYW1s
            YUdGWTVqQWErT205NHR6bkFySGxqSzgKLS0tIFc2NENmSXcvdUZHZjRNeDBFNk5x
            TER6QmpVYjE4STlqaE02MXBqdEg5d0kK2CoegbJOPb1JbFB9a+Rpc9s2UtCPJsex
            uopI4c9ssiD2NBEjZbfJNKo561cHFMd7Ur3EzIbiFxCijdnQCSxWxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T17:58:30Z"
    mac: ENC[AES256_GCM,data:IMrklbLwf0YGhb/FWMHWEwD4EOD3ch6VU2HqFuKoNOQim5JVM/1/0wxryFbbFpIfm0Wf/oHSVqdlxmod+CMrHfymHz595HDLDsJ1azcz2YH9LGC+9FZKoxmQD4JLsNKaZixA2OJCFUJ+LlxkY6xL3SU71Wutq9ENh0Vxjz1j0iU=,iv:R+zpyMISSP6zr0Abxuzj9WFBTUNKYSGLRnMbavuFK3U=,tag:6wWQo3A6M6QRRgtKmofafg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
