apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: devtron-public
  namespace: devtroncd
spec:
  endpoints:
    - dnsName: cloud.dvflw.co
      recordType: A
      targets:
        - 104.14.105.18
