apiVersion: v1
kind: Secret
metadata:
    name: devtron-values
    namespace: devtroncd
stringData:
    values.yaml: ENC[AES256_GCM,data:sQrbzdW9rckibMJyKEHGBiJQy59zF6s+Bjr40Gz0KGsA4AuTWLZCxCfvpJj7p60uCHhIokX1eCkkYhVwOEqvOVw1eltkuXI0BnY74rnBULo39kDpnmkGSyvWng8lk97umjmcj9xTzsQfG+L/fnFVE/WbS7MqJwkNgNa7XyE/yl+Wo2sxGKRIX+5p6ye60zK9O/Y/jMXfadNq8+em1f04O8Eyl6soO9m7a+etp7nuS0KGjsNQ2z1rx/O6vqlJJNlk5+J3ywdi5gYxd124MCrfdacG6ea/udcnoBbK1tqX+Ymn1Iq3mQ==,iv:cEe22ckIoEF38VskZ2o6ZF1DnrUvrkOM4SXtBK25I84=,tag:he0VWt3XH33ccyGJlKcESg==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bXhwbTAyYjc3eFVvdTF0
            NlRIeitrTDlUcGlvQUEvUWJZeHNXSVVZR2lNCnU4V3prSjRLM0hPc09ua0YzbXlT
            NnI5VlFWUU5WN3R6bXlxZ0tNUENSYk0KLS0tIE9qbjRQeFNmRnJwcW5rS2EyMGU0
            dmMwN0F1MW91ZUdhcm9NaVVjWnhCNXMKHNFi3sxpPR8w8ehj2Gtfk0ObSSCW8D0H
            M/ElXaXKN+Cc+RJKop4u5VtYf4PYO9SPhQM7oOK83rEKDJnNB8rmJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-10T05:24:34Z"
    mac: ENC[AES256_GCM,data:Bj2EznvnnzOrca89BIgQrUb6fLfoWERYwJNBeJM8/wyednRKH83pZUanE/I9qk1JaKyobTn2+UkIi4+xawIJcD0sbpp4BDJY/BJCaRzvavqrdKljHchubgcmWSrDhDmFfuzPbLCQ9czgEjgMaCDfqX4BiRHU/OndiPpAYdXIT58=,iv:gsZrMIL23lqXC9HXig53oZEMTIKvSUZUvYgvy/zkG2Y=,tag:GlfLACV7zPz7WneZEG9jeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
