apiVersion: application.kubero.dev/v1alpha1
kind: Kubero
metadata:
  name: kubero
  namespace: kubero
spec:
  fullnameOverride: kubero
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/kubero-dev/kubero/kubero
    tag: "v3.1.1"
  ingress:
    enabled: false
  kubero:
    context: inClusterContext
    namespace: kubero
    webhook_url: https://kubero.home.mcnees.me/api/repo/webhooks
    config:
      clusterissuer: letsencrypt-production
      kubero:
        readonly: false
        admin:
          disabled: false
        console:
          enabled: false
      templates:
        enabled: true
        catalogs:
          - name: Kubero
            description: Kubero templates
            templateBasePath: https://raw.githubusercontent.com/kubero-dev/kubero/main/services/
            index:
              url: https://raw.githubusercontent.com/kubero-dev/templates/main/index.json
              format: json
          - name: Kubero Frameworks
            description: Kubero framework templates
            templateBasePath: https://raw.githubusercontent.com/kubero-dev/kubero/main/services/
            index:
              url: https://raw.githubusercontent.com/kubero-dev/templates/main/index-frameworks.json
              format: json
  prometheus:
    enabled: true
    endpoint: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
  registry:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  service:
    port: 2000
    type: ClusterIP
