apiVersion: v1
data:
    KUBERO_ADMIN_PASSWORD: ENC[AES256_GCM,data:tiQwmbG9FnetZZlR+9+13z7QvMy2GjR2K42ODiuPZx1PVZ1mkRtin4asJU8=,iv:wTmNCYGOKjShYqc0CA1jc2nAWueWrTGtrmsVPmG4QpQ=,tag:y9yR9xgURz+h41mqZbxMew==,type:str]
    KUBERO_ADMIN_USERNAME: ENC[AES256_GCM,data:LOO9YbQDLv0=,iv:hL+4GB1+hSBUNFgNftT3lra55fwgrDSiNnVF/5XE/a0=,tag:XSe87BpsbrqCPC5TBhx2iQ==,type:str]
    KUBERO_SESSION_KEY: ENC[AES256_GCM,data:ffW37TXeN44XS3tS9omdQqLTcdKAXHXfkL7ZD2SE+7ovUzoU7re1aB48Nb5odAhUr4O9bDtiIdPMVLKoZG5hYJsDAVObpJuDhBAMdlG5DGlw5rGtx02zcg==,iv:nA4WJqNm/B1myYE8zRXymcJuDqvR5Xx9ztQmXaIVAPg=,tag:iocYgFgpfcY1dTR8aXMDsQ==,type:str]
    KUBERO_WEBHOOK_SECRET: ENC[AES256_GCM,data:yrQHGE5gMkZxNXEj2fDlY/QOG/ZY7CjiAqP53Ap1/yHf2uhLnP4uncehx9g4fluiSosXRQ+JWlI=,iv:NbZMlA4nbgx5fT4jLyc7RgwGpWZRgFut5VvgDpIaIuI=,tag:5wqNMnuGtroW+turOfcwEg==,type:str]
kind: Secret
metadata:
    name: kubero-secrets
    namespace: kubero
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTTNKYnE0TWVUNHBneVRk
            OEgvLzhwdTgvQ1RaMXpQS0tacHQ4am1GVkNvCjJvamtkbk9veWhBUGVFUXVFQ0lQ
            ZlpTai9qUVArWjFwMHd3RWhQUGErSDgKLS0tIGx0cW9sTjhnT0tBVFF4VTM2OStv
            V2RuNjU2STgzVkIzK001QXRMdWZKS00Kzh2lGc+GwA4rP2aVeAPF6PPx3BMJyqYI
            1cAfDQaaFLPtPsNuigC/vGXKjH6qkZvTf40w67ucH0HDyY+IPDvs3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T04:06:55Z"
    mac: ENC[AES256_GCM,data:v7/NGe4KBw8p+T0HBiWNTjTXZlpkdlH94dKCga4TpTY01rdWF6nele4pNpXmooq7/q/O8cFWuWwAPKJfqTvOFvEysPHn7cky7GXeN3iInJhUXTDO+hbZ6KwIpFfOzDsOD9wR117mTp+n3S4+W9NRK8BGHBKwiL+2RDwXUIDPrdc=,iv:9t+sQPrUg8eufOLLKX5TOXOAevgGy0qWIQpn2z3tUmc=,tag:7nPGFpfGrqdlyXHCAST7OA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
