apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
