apiVersion: v1
kind: Secret
metadata:
    name: rustfs-secrets
    namespace: object-storage
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:7MsMGQDywcUjuy6HMscvcGXlWmfY29ey/AZCJ9bam3s=,iv:BbnJyd0qE3bJkPq0x+qMS2rTyMzNtxA8z/g/nsh+W68=,tag:QDyCIT5DylOSW19YdZ6rXw==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:yY2DFV3SDZKEKeeRSVTFr0QBp9kSjG9nXjSXpKnw+l8UequxsOcqBfs+uacotGNj,iv:fr3/4HBFtynyWZeaj/0t8WKN9weilKrU4uQmTl+oPR8=,tag:iS5tP7MnSZiOlBFo/TxIQA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTkRzZ0VmNjRSTXBhZWNQ
            MzZReWtwSzdQMmQ3ZWVPNTEyTVgwVUhWZldJCnl2Y3dyOUd4ZmhjZitZb0w0aEdG
            aUc3Y2VXOUxPa3lHYVRDcW1YVWtJSXcKLS0tIDZRaTFyWDVLOHNQdkYwTk9kcWM3
            RHROTUhTZ3Q4ZWdnQjFMYndtRUNRSFUKqxAPSBhvs0Fypz7NKiOKRIMsZS0AIdMM
            otasDrpoj+lCMVjPG3vBQcL7wFvNBYqHG4mCCaMm0EkvMeymEsj41w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T01:10:25Z"
    mac: ENC[AES256_GCM,data:TPLDKqnnHnU2ISlkUbaDpkNXyFgNfTsvNzXBe0G1CnOn3oxDbUQ3jnJq5RSlsm2bgLTmqCRnkq3XMGC/6l1EfeJApzX5m961+nbu+OXrrUOqa0if3F7ULUwyBQHTnN0/bX4ciFWAMReuXesEslg3lC+2NIs7FdPGsYc+a/hbZDw=,iv:EDmbQTXyiYbzXMO9xtet0esL5ZmhObNdH8wZ5WF139M=,tag:JNw5Agu8TDq4+CnUXIOEIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
