apiVersion: v1
kind: Secret
metadata:
    name: rustfs-secrets
    namespace: storage
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:7hidE9LNvsb8+FMDwiBR4SS5Jdfw5AHI3e46aFCQkt8=,iv:4EmeHlZ4uNGLCBW2E2yVyMDuWvCQfVJ/36/L6lrxq6w=,tag:K/6LZQqLR39VMMr6JV1FcA==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:6AwkrLJQ2cI1JyVBPuzPOi1qYzh0tLHeL7N5E+A0vqrkhrAKtjh2wQQoCIxAnuLo,iv:eu+ULzm4LlLCyzQQEtB37I9/Z6jdVRCH5bPqkpuod/4=,tag:+pEsTlawI9/id1yzLAxs+w==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d053U2FnUFF0QVFwVGFl
            RnVpMFFSWkNmd0pPZXFCMlBVM1piWHplU1NrCmpLUDZTdlU5M2wwWXlTRzh5UGQ5
            WVQ1K3I1alFSMlpXZys3Y0puRU1HK0UKLS0tIG9FdXQ4QXBZdWU2SURHQzlZMk0y
            YWo2bmFjK0ttbEw2QzdqaVdpMlJuWFEK6O2pv+a4O/JfhA2AjwgUclcHm6MIG7zK
            XOf82i8paqNitHY/pBYzQ4OLgzNh/ifCbdAQBdz9w3Y4ge1Tuc+YLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T02:41:10Z"
    mac: ENC[AES256_GCM,data:VuxXpFUx8LxGeYSxg866U4CyhjLugbp7QwpIXlSvz/f0OKX4XO2uBAdv+r835s8vrsPbmakk7qjfUOuiZQjcY5POUsO/1XgoahQq0Xqtclfj0h//fH1VxdpBnyMI6MVQybGsiEAa+J9FhqG0T5OiKyjASS+Ox7TrBH7NBirCWBI=,iv:y8ZcRk5dC8EKxcBG2oj84krAKyhMO0Wg8TRIYfdNvt0=,tag:2R0EWo2crloO/mff9G6rUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
