apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grimmory
  namespace: apps
spec:
  entryPoints:
    - websecure-external
  routes:
    - match: Host(`library.mcnees.me`)
      kind: Rule
      middlewares:
        - name: public-chain
          namespace: infrastructure
      services:
        - name: grimmory
          port: 6060
  tls:
    secretName: legacy-public-wildcard-tls
