apiVersion: v1
kind: Secret
metadata:
    name: grimmory-secret
    namespace: apps
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:JAzppFpuyB5NMODmRB8R7eV6FXmTUsBNmSnlcdigjEu2FwJ5mZQGwFXDTVyONHonLnQa9xLVC+MDR/DHiBv9Mg==,iv:sgwyWnqk6+X50tndGr7xXy+6IPe8PeYZgqnWi8cA74I=,tag:p/VbGqzVC2b9xRcDjEsghg==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:Di7l18CSbArdHPqLzEHj/ks3O/Kwlkr/2bODph+6m9m9G9G1BJFGKZSSL5UdsDOMsnB7dpFdvJ4kbuqbMkVx1w==,iv:4R9N9H3g88/FJ+kEGSR9P4jMHAEHIRP36VXJ+Tnz060=,tag:Gf6Rrqp5pzWm6/3Y5cklQg==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcmRPOFZ1OFhHaFc3cUFa
            YTJPbkF6S3lYeCtja2VXNWVWYU1Jd01NdkZrCkJMWWtid1Q2VUVMZ1Zkcy83c01R
            TVBSTUdrVDdOMGthREtjeTdNQ00wclkKLS0tIHRTcFljcEQvbGwyano2dm5sQm5S
            Szg4Z1VOd1N3bUM4REd5NU9lVHQxalUKfgD4zKwYpPX/K89Ow35jQrs1Mz0AJ5nn
            IBq8J2agHd7681iUzv4upMnJN6JzJ+9VfNCOYhkAQRQmrn1YBjM8DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T03:14:27Z"
    mac: ENC[AES256_GCM,data:KrhthSTj2bjBcuuOAwGWdNPSCwr9IpSCfOehFcqVyV9noixiR/WBCC4TjfAGA1UBYVSgAjdAV1b+2L6y8VpaIARYwr0+2JODOGS1vOtPoAAUyshOUQIhSN2ndhw06cuiCe55JdtP0kBS3oq0xqFrnIFbYAepQtohdGzymtGLgus=,iv:bCGM29JGEQoT/6hsF8ikL7Ybel67qAAHi+yJ3ZHDe80=,tag:l1CNxuw+6s6fr/A/eQBi4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
