apiVersion: v1
kind: Service
metadata:
  name: grimmory
  namespace: apps
  labels:
    app.kubernetes.io/name: grimmory
spec:
  ports:
    - name: http
      port: 6060
      targetPort: http
  selector:
    app.kubernetes.io/name: grimmory
