apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - restic-password-secret.sops.yaml
  - restic-init-job.yaml
  - mariadb-grimmory-credentials.sops.yaml
  - mariadb-grimmory-cronjob.yaml
  - adguard-config-backup-cronjob.yaml
  - backup-metrics-exporter.yaml
  - backup-alerts.yaml
