# Use a dedicated read-only backup user, not the app's master user.
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-grimmory-backup-credentials
    namespace: apps
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:En1C8kEx2xvioqIGT6Y=,iv:V/6gwZ7HtL5oYH0EbIN7zZ4X74hd4L4o9apxyNFnqU8=,tag:iMYriFis6AYwXNquODy5Vg==,type:str]
    PASSWORD: ENC[AES256_GCM,data:MomX1suyQtJDq7mBMaRjZj2ITGmxsgqx5ppIc7hTt8g2UjQq3S6Ya/x7QCo=,iv:fxyK9l6PmEY4c4hTNVwoIR5UYrffiDRYb0kkdtygAPI=,tag:Bp/R14LRuyJUHX5TwZlSZg==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QUVoemhUSjdVTHFGS2d0
            TnlvWFRWZHZnMnNXdXhkeE1pQW5XNEs1RVIwCldUZjYrWEFRbUZqSW9QbWtkQmU2
            a29lUkN0b0xRYnJUUVF3SXhoU2VZSGMKLS0tIG1QUEppMVdTU2FOdm02RG9ESUVa
            SnpnZFN3emxjQ0cvMEQ1V2NmenQvVVEKXBFhJ+H0eGQh5bHBaROQ8B39mfwovsld
            kkZGzRAVQTotJu9Wz2tZRgj3iK15KIHyaAqaujloHPB5HUBhtETQig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:10:18Z"
    mac: ENC[AES256_GCM,data:2U1Gw500JNndM+KtiWaxZb5jyNCEQyKrOgrpDmyMCQ1Gq6TS6O5o5AsW9yz4oZS2iO4JnfQHkDZzEx1Dd/Ey72AKghy1YCwwUFDmdXEnmNzFQ4we/lvOrf3SSmujWKXMyB+fuFeU+wPQXqLWr62uCSDnZ2C2LmUy+5a4pQ2i1tg=,iv:7E0e816bY/Z72WIsAlwUiQlub0gAxQk3wOZd+EjDEbI=,tag:I6CSRx1ul8N/6PWIi3t6dw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
