# This same secret is duplicated into every namespace that runs a backup
# CronJob (apps, media, internal). All replicas hold the same password — losing
# it means the restic repository is unrecoverable.
apiVersion: v1
kind: Secret
metadata:
    name: restic-password
    namespace: internal
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:/YCpeZJAzByrc+u6mJOtraYQ5mzLpYnqhaveSYYzdpygFiQMPIClBPO58NA=,iv:/6Qp1NvvnL/3PaDAVBm+5oU+dd6GFXDaPi9KY2dsMfs=,tag:+O23Z4tguY2Hig/KZziWLQ==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaC84d1FjRUhJUjh1VUVO
            TmVneUFWbjg0MTVuVmZPM1lQZ2hVS0Q3T21rCnNrdXppVXBDSFFaVmNuMzdZSEdN
            elMrdklxam92M1NLTHlEdFl4MHZLRU0KLS0tIHJRd1FoMmdoMi9senRLZDZwdXEy
            K01DYTFQVklBZGlXNXlaYWZ1UTFwdE0KajNsmdjl0Qr1iHUGTVCJucqgFXlFXDU2
            reBccAgQ4tCOTmgzOY+KLZh2dr683dho74hPFNKxM+aAjsIVHhTHLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:08:11Z"
    mac: ENC[AES256_GCM,data:rjLgZj3RcQi8f9LKy++pVvcGo5H+FWzaFfXEQPaTUzpp4hkQGns9ZzJ/MLwA10xUci1E9FQBx9UjoHAqotpHSxN+2KoN19Gy8J7X3e/DLL4owvAzalMleEEzzEuirjMD3ns06/mzU3ZieeAMmCGWyf+WIjD6OaF0/FdXpYDarFE=,iv:pQvPMODVnU4yAxIDcHUyhlvvZ40Xd7P0zX6zCU4nkRU=,tag:UsDgm/6b5jAhA6I/TVBwgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-password
    namespace: apps
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:BJPcxYPwEMLXanC+i8WN/RGRMU9o40miZ2zwhQbYgyfHt7617ci9eX8YrYM=,iv:EaLrOkJ9gITYQslDpLXuKzESbfJKe37TvcXzSHNjLuI=,tag:S5c5Qvnh91dVBURCHGp2NA==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaC84d1FjRUhJUjh1VUVO
            TmVneUFWbjg0MTVuVmZPM1lQZ2hVS0Q3T21rCnNrdXppVXBDSFFaVmNuMzdZSEdN
            elMrdklxam92M1NLTHlEdFl4MHZLRU0KLS0tIHJRd1FoMmdoMi9senRLZDZwdXEy
            K01DYTFQVklBZGlXNXlaYWZ1UTFwdE0KajNsmdjl0Qr1iHUGTVCJucqgFXlFXDU2
            reBccAgQ4tCOTmgzOY+KLZh2dr683dho74hPFNKxM+aAjsIVHhTHLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:08:11Z"
    mac: ENC[AES256_GCM,data:rjLgZj3RcQi8f9LKy++pVvcGo5H+FWzaFfXEQPaTUzpp4hkQGns9ZzJ/MLwA10xUci1E9FQBx9UjoHAqotpHSxN+2KoN19Gy8J7X3e/DLL4owvAzalMleEEzzEuirjMD3ns06/mzU3ZieeAMmCGWyf+WIjD6OaF0/FdXpYDarFE=,iv:pQvPMODVnU4yAxIDcHUyhlvvZ40Xd7P0zX6zCU4nkRU=,tag:UsDgm/6b5jAhA6I/TVBwgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-password
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:hMzwfM9n0wPCHRwBHRMcRsY0YOWntAF0kX07hPQH1eTYkEzdryj00SpJUHw=,iv:+rIM76Xx/W6JLjZ3G6bim8doH2PdCHpxFsu7Z19AL4w=,tag:r4bzXPRwTX8LZwR4+DFrww==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaC84d1FjRUhJUjh1VUVO
            TmVneUFWbjg0MTVuVmZPM1lQZ2hVS0Q3T21rCnNrdXppVXBDSFFaVmNuMzdZSEdN
            elMrdklxam92M1NLTHlEdFl4MHZLRU0KLS0tIHJRd1FoMmdoMi9senRLZDZwdXEy
            K01DYTFQVklBZGlXNXlaYWZ1UTFwdE0KajNsmdjl0Qr1iHUGTVCJucqgFXlFXDU2
            reBccAgQ4tCOTmgzOY+KLZh2dr683dho74hPFNKxM+aAjsIVHhTHLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:08:11Z"
    mac: ENC[AES256_GCM,data:rjLgZj3RcQi8f9LKy++pVvcGo5H+FWzaFfXEQPaTUzpp4hkQGns9ZzJ/MLwA10xUci1E9FQBx9UjoHAqotpHSxN+2KoN19Gy8J7X3e/DLL4owvAzalMleEEzzEuirjMD3ns06/mzU3ZieeAMmCGWyf+WIjD6OaF0/FdXpYDarFE=,iv:pQvPMODVnU4yAxIDcHUyhlvvZ40Xd7P0zX6zCU4nkRU=,tag:UsDgm/6b5jAhA6I/TVBwgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-password
    namespace: observability
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:QfA74U5cvF+FFYA2bROJcUxvkGjn84lH5xD3C2CKcecbkcfyYYMqHs9bwQs=,iv:YDFD6XRJIMBebA8WBp9kpLg6henXlU1bAqvHhY8G0gw=,tag:iyMGs5QtZQbh7kfiWgjxtw==,type:str]
sops:
    age:
        - recipient: age1zfnym5p8v5rj3rvvufmmk47k4t9zg8v74ymktcmcr09e60724u4swyta6q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaC84d1FjRUhJUjh1VUVO
            TmVneUFWbjg0MTVuVmZPM1lQZ2hVS0Q3T21rCnNrdXppVXBDSFFaVmNuMzdZSEdN
            elMrdklxam92M1NLTHlEdFl4MHZLRU0KLS0tIHJRd1FoMmdoMi9senRLZDZwdXEy
            K01DYTFQVklBZGlXNXlaYWZ1UTFwdE0KajNsmdjl0Qr1iHUGTVCJucqgFXlFXDU2
            reBccAgQ4tCOTmgzOY+KLZh2dr683dho74hPFNKxM+aAjsIVHhTHLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:08:11Z"
    mac: ENC[AES256_GCM,data:rjLgZj3RcQi8f9LKy++pVvcGo5H+FWzaFfXEQPaTUzpp4hkQGns9ZzJ/MLwA10xUci1E9FQBx9UjoHAqotpHSxN+2KoN19Gy8J7X3e/DLL4owvAzalMleEEzzEuirjMD3ns06/mzU3ZieeAMmCGWyf+WIjD6OaF0/FdXpYDarFE=,iv:pQvPMODVnU4yAxIDcHUyhlvvZ40Xd7P0zX6zCU4nkRU=,tag:UsDgm/6b5jAhA6I/TVBwgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
