apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./beszel
  - ./loki
  - ./alloy
  - ./blackbox-exporter
  - ./ollama-exporter
  - ./version-checker
  - ./proxmox-exporter
  - ./unpoller
  - ./kube-prometheus-stack
